/**
 * ============================================================
 *  TRIZA — Auto-Generated Knowledge Batch
 * ============================================================
 *
 *  Generated by scripts/generate-knowledge.ts using z-ai CLI.
 *  DO NOT EDIT BY HAND.
 *
 *  To regenerate:  bun run scripts/generate-knowledge.ts
 *  To add topics:  edit scripts/topics.json
 *
 *  Generated: 2026-07-02T14:42:18.146Z
 *  Entries: 2
 * ============================================================
 */

import type { KnowledgeEntry } from './types'

export const AUTO_GENERATED_ENTRIES: KnowledgeEntry[] = [
  {
    id: 'test-crispr',
    patterns: [/\b(crispr|gene editing|cas9|genetic modification|dna editing|molecular scissors|genome editing|synthetic biology)\b/i],
    keywords: ['biotechnology', 'genetics', 'dna', 'rna', 'precise editing', 'genetic engineering', 'therapeutic applications', 'agricultural biotechnology', 'ethical concerns', 'molecular biology'],
    intent: 'factual_question',
    topic: 'biology',
    response: () => `CRISPR gene editing is a revolutionary **biotechnology** tool that allows scientists to make precise changes to an organism's **DNA**. Derived from a natural bacterial immune system, CRISPR has transformed **genetics** research and opened new possibilities for treating diseases, improving crops, and understanding gene function. This technology is often described as 'molecular scissors' due to its ability to cut and modify genetic material with unprecedented accuracy.

### How CRISPR Works
CRISPR relies on a system of **RNA**-guided enzymes, primarily **Cas9**, which acts as molecular scissors. The process involves designing a guide RNA (gRNA) that matches the target DNA sequence. When the gRNA binds to the complementary DNA, Cas9 cuts the DNA at that specific location. The cell's natural repair mechanisms then either fix the break (often introducing small errors) or allow scientists to insert new genetic material. This precision makes CRISPR far more efficient and accessible than previous gene-editing methods.

### Applications in Medicine
In **medicine**, CRISPR holds immense potential for treating genetic disorders like sickle cell anemia, cystic fibrosis, and Huntington's disease. Researchers are also exploring its use in cancer therapy by editing immune cells to better target tumors. Additionally, CRISPR is being investigated for infectious diseases, such as disabling viruses like HIV or creating mosquitoes resistant to malaria. However, ethical concerns, particularly around germline editing (changes passed to future generations), remain a significant hurdle.

### Agricultural and Environmental Uses
CRISPR is revolutionizing **agricultural biotechnology** by enabling the development of crops with improved yields, drought resistance, and nutritional content. For example, scientists have created disease-resistant rice and tomatoes with extended shelf life. In environmental science, CRISPR is used to study and potentially control invasive species or restore endangered populations by editing their genomes to enhance survival.

### Challenges and Ethical Considerations
Despite its promise, CRISPR raises **ethical concerns**, including off-target effects (unintended DNA changes), accessibility disparities, and the potential for misuse in human enhancement. Regulatory frameworks are still evolving to ensure responsible use. Public engagement and transparency are critical to addressing these issues and fostering trust in this powerful technology.

### Why It Matters
CRISPR gene editing represents a paradigm shift in **biology**, offering tools to solve some of humanity's most pressing challenges. From curing genetic diseases to securing global food supplies, its applications are vast and transformative. As the technology advances, balancing innovation with ethical responsibility will be key to harnessing its full potential for the benefit of society.`,
  },

  {
    id: 'test-blackhole',
    patterns: [/\b(event horizon|black hole boundary|point of no return|escape velocity|singularity)\b/i],
    keywords: ['black hole', 'event horizon', 'spacetime', 'gravity', 'singularity', 'accretion disk', 'hawking radiation', 'relativity', 'cosmos'],
    intent: 'factual_question',
    topic: 'space',
    response: () => `The **event horizon** is a critical boundary surrounding a **black hole**, marking the point of no return for anything, including light. This invisible threshold is where the gravitational pull becomes so immense that not even the fastest-known particles can escape. It is a fundamental concept in astrophysics, rooted in Einstein's theory of general relativity, which describes gravity as the warping of **spacetime** by mass and energy.

### What Is the Event Horizon?
The event horizon is not a physical surface but a region in **spacetime** where the escape velocity exceeds the speed of light. Once an object crosses this boundary, it is inexorably pulled toward the **singularity**—the infinitely dense core of the black hole. The size of the event horizon is directly related to the black hole's mass; more massive black holes have larger event horizons. For example, a black hole with the mass of the Sun would have an event horizon approximately 3 kilometers in radius.

### Formation and Structure
Event horizons form when massive stars collapse under their own gravity during a supernova, leaving behind a black hole. The boundary is defined by the **Schwarzschild radius**, a mathematical concept derived from general relativity. Outside the event horizon, the gravitational effects are extreme but not inescapable. Inside, however, all paths lead to the singularity, making it a one-way journey for matter and energy.

### Observational Challenges
Detecting event horizons directly is impossible because no information can escape from within them. However, scientists infer their existence by observing the behavior of nearby matter. As material falls toward a black hole, it forms an **accretion disk**, emitting intense radiation before crossing the event horizon. Telescopes like the Event Horizon Telescope have captured images of these accretion disks, providing indirect evidence of event horizons.

### Why It Matters
The study of event horizons is crucial for understanding the extreme physics of the universe. They challenge our comprehension of gravity, spacetime, and the laws of physics. Moreover, phenomena like **Hawking radiation**, which suggests black holes can slowly evaporate, highlight the interplay between quantum mechanics and general relativity. By studying event horizons, scientists push the boundaries of human knowledge, offering insights into the nature of reality itself.`,
  },
]
