/**
 * ============================================================
 *  TOPIC PACKS — Bulk knowledge collection ke liye preset lists
 * ============================================================
 *
 *  User ek baar mein "sara internet ka data" collect karna chahti
 *  hain. Literally pura internet crawl karna impossible hai
 *  (petabytes, saalon ka kaam, legal issues). Lekin HUNDREDS of
 *  curated topics ko ek hi waqt mein harvest karna bilkul mumkin
 *  hai — yeh ChatGPT-level broad knowledge ka practical version hai.
 *
 *  Har pack ek domain cover karta hai (Science, History, etc.).
 *  User checkbox se packs choose kare, ya apni custom topic list
 *  paste kare. Phir Bulk Harvest button dabaye — agent sab topics
 *  par internet se search + read karke knowledge store mein daal
 *  dega.
 * ============================================================
 */

export interface TopicPack {
  id: string
  name: string
  urduName: string
  emoji: string
  color: string // tailwind gradient classes
  accent: string // tailwind text color
  description: string
  topics: string[]
}

export const TOPIC_PACKS: TopicPack[] = [
  {
    id: 'science',
    name: 'Science',
    urduName: 'Science',
    emoji: '🔬',
    color: 'from-cyan-500 to-teal-600',
    accent: 'text-cyan-600',
    description: 'Physics, chemistry, biology ke bunyaadi topics',
    topics: [
      'photosynthesis',
      'gravity',
      'evolution',
      'DNA structure',
      'atoms and molecules',
      'periodic table',
      'electricity',
      'magnetism',
      'light properties',
      'sound waves',
      'thermodynamics',
      'theory of relativity',
      'quantum mechanics basics',
      'cell biology',
      'genetics and heredity',
      'ecosystems',
      'climate change causes',
      'renewable energy sources',
      'fossil fuels',
      'nuclear energy',
      'water cycle',
      'carbon cycle',
      'cellular respiration',
      'mitosis and meiosis',
      'enzymes function',
      'proteins structure',
      'vitamins and minerals',
      'states of matter',
      'chemical reactions',
      'acids and bases',
    ],
  },
  {
    id: 'history',
    name: 'History',
    urduName: 'Tareekh',
    emoji: '📜',
    color: 'from-amber-500 to-orange-600',
    accent: 'text-amber-600',
    description: 'World aur regional history ke ahem waqiat',
    topics: [
      'world war 1 causes',
      'world war 2 causes',
      'cold war',
      'french revolution',
      'american revolution',
      'industrial revolution',
      'renaissance period',
      'ancient egypt civilization',
      'roman empire',
      'ancient greek civilization',
      'mughal empire',
      'ottoman empire',
      'british empire',
      'mongol empire',
      'indus valley civilization',
      'partition of india 1947',
      'pakistan independence movement',
      'silk road trade route',
      'age of exploration',
      'the crusades',
      'black death plague',
      'the holocaust',
      'vietnam war',
      'korean war',
      'gulf war',
      'apartheid in south africa',
      'civil rights movement',
      'fall of berlin wall',
      'soviet union collapse',
      'ancient mesopotamia',
    ],
  },
  {
    id: 'geography',
    name: 'Geography',
    urduName: 'Geography',
    emoji: '🌍',
    color: 'from-emerald-500 to-green-600',
    accent: 'text-emerald-600',
    description: 'Duniya ke continents, mountains, rivers, deserts',
    topics: [
      'seven continents',
      'five oceans of the world',
      'highest mountains in the world',
      'longest rivers in the world',
      'largest deserts in the world',
      'tropical rainforests',
      'climate zones of earth',
      'tectonic plates',
      'how volcanoes form',
      'how earthquakes happen',
      'how tsunamis form',
      'glaciers and ice caps',
      'amazon rainforest',
      'himalayan mountain range',
      'mount everest',
      'nile river',
      'amazon river',
      'pacific ocean',
      'antarctica continent',
      'sahara desert',
      'gobi desert',
      'great barrier reef',
      'grand canyon',
      'great wall of china',
      'nile delta',
    ],
  },
  {
    id: 'pakistan',
    name: 'Pakistan',
    urduName: 'Pakistan',
    emoji: '🇵🇰',
    color: 'from-green-600 to-emerald-700',
    accent: 'text-green-700',
    description: 'Pakistan ki history, geography, culture, aur log',
    topics: [
      'pakistan history',
      'pakistan geography',
      'lahore city',
      'karachi city',
      'islamabad capital',
      'punjab province',
      'sindh province',
      'balochistan province',
      'khyber pakhtunkhwa province',
      'gilgit baltistan region',
      'mohenjo daro',
      'harappa civilization',
      'quaid e azam muhammad ali jinnah',
      'allama iqbal poet',
      'pakistan independence 1947',
      'indo pak wars',
      'kashmir dispute',
      'pakistan economy overview',
      'pakistani culture and traditions',
      'urdu language history',
      'punjabi language',
      'sindhi language',
      'pashto language',
      'pakistani cuisine',
      'pakistan national symbols',
      'k2 mountain pakistan',
      'indus river pakistan',
      'pakistani festivals',
      'pakistan cricket team',
      'pakistan national anthem',
    ],
  },
  {
    id: 'technology',
    name: 'Technology',
    urduName: 'Technology',
    emoji: '💻',
    color: 'from-slate-600 to-gray-700',
    accent: 'text-slate-600',
    description: 'Computers, internet, AI, aur modern tech',
    topics: [
      'artificial intelligence basics',
      'machine learning basics',
      'blockchain technology',
      'cryptocurrency bitcoin',
      'history of internet',
      'world wide web',
      'computer programming',
      'python programming language',
      'javascript programming',
      'database management',
      'cloud computing',
      'cybersecurity basics',
      'data science',
      'internet of things',
      '5g technology',
      'quantum computing',
      'robotics engineering',
      'virtual reality',
      'augmented reality',
      '3d printing technology',
      'self driving cars',
      'drone technology',
      'social media impact',
      'e commerce business',
      'mobile app development',
    ],
  },
  {
    id: 'health',
    name: 'Health',
    urduName: 'Sehat',
    emoji: '⚕️',
    color: 'from-rose-500 to-pink-600',
    accent: 'text-rose-600',
    description: 'Sehat, nutrition, aur medical knowledge',
    topics: [
      'human nutrition basics',
      'benefits of exercise',
      'importance of sleep',
      'mental health awareness',
      'stress management techniques',
      'healthy diet guidelines',
      'essential vitamins',
      'protein in diet',
      'carbohydrates function',
      'healthy fats',
      'importance of hydration',
      'weight loss basics',
      'diabetes type 2',
      'hypertension high blood pressure',
      'heart disease prevention',
      'cancer types and prevention',
      'immune system function',
      'digestive system',
      'brain health',
      'bone health and calcium',
      'skin care basics',
      'dental health',
      'eye health care',
      'pregnancy care',
      'child development stages',
    ],
  },
  {
    id: 'islam',
    name: 'Islam',
    urduName: 'Islam',
    emoji: '🕌',
    color: 'from-teal-600 to-cyan-700',
    accent: 'text-teal-700',
    description: 'Islamic knowledge, history, aur practices',
    topics: [
      'five pillars of islam',
      'the holy quran',
      'prophet muhammad life',
      'salah prayer in islam',
      'zakat charity',
      'fasting in ramadan',
      'hajj pilgrimage',
      'month of ramadan',
      'eid al fitr',
      'eid al adha',
      'mosque in islam',
      'islamic history overview',
      'the four caliphs',
      'sunni and shia differences',
      'islamic art and calligraphy',
      'islamic architecture',
      'islamic finance principles',
      'halal food rules',
      'islamic ethics and morality',
      'islamic festivals',
    ],
  },
  {
    id: 'general',
    name: 'General Knowledge',
    urduName: 'Aam Ilm',
    emoji: '💡',
    color: 'from-violet-500 to-purple-600',
    accent: 'text-violet-600',
    description: 'Aam maloomat — duniya ke bare mein basic facts',
    topics: [
      'solar system planets',
      'the sun',
      'the moon',
      'stars and constellations',
      'what are black holes',
      'galaxies in universe',
      'how the universe began',
      'big bang theory',
      'dinosaurs extinction',
      'human body systems',
      'how the brain works',
      'how the heart works',
      'how lungs work',
      'how kidneys work',
      'human blood composition',
      'what is DNA',
      'theory of evolution',
      'what is photosynthesis',
      'what causes gravity',
      'what is electricity',
      'what is magnetism',
      'properties of light',
      'how sound travels',
      'forms of energy',
      'states of matter',
      'what are atoms',
      'what are molecules',
      'chemical elements',
      'water properties',
      'oxygen importance',
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    urduName: 'Khel',
    emoji: '⚽',
    color: 'from-orange-500 to-red-600',
    accent: 'text-orange-600',
    description: 'Sports, games, aur athletes ki maloomat',
    topics: [
      'cricket rules and history',
      'football soccer rules',
      'field hockey game',
      'tennis sport',
      'basketball game',
      'olympic games history',
      'fifa world cup',
      'cricket world cup',
      'pakistan cricket history',
      'pakistan hockey achievements',
      'mountaineering sport',
      'boxing sport',
      'wrestling sport',
      'swimming sport',
      'track and field athletics',
      'cycling sport',
      'golf game rules',
      'rugby sport',
      'baseball game',
      'badminton sport',
    ],
  },
  {
    id: 'everyday',
    name: 'Everyday Life',
    urduName: 'Roz Marra',
    emoji: '🍳',
    color: 'from-lime-500 to-green-600',
    accent: 'text-lime-600',
    description: 'Rozana ki zindagi ke useful skills aur tips',
    topics: [
      'how to cook biryani',
      'how to make chai tea',
      'how to tie shoelaces',
      'how to ride a bicycle',
      'how to learn driving',
      'how to write a resume',
      'how to save money',
      'how to manage time',
      'how to reduce stress',
      'how to learn english',
      'how to improve memory',
      'how to stay healthy',
      'how to grow plants',
      'how to recycle waste',
      'how to stay safe online',
      'how to cook rice perfectly',
      'how to make bread at home',
      'how to clean a house',
      'how to budget monthly expenses',
      'how to start a small business',
      'how to communicate effectively',
      'how to solve problems',
      'how to build good habits',
      'how to read more books',
      'how to stay motivated',
    ],
  },
]

/** Get a flat list of all topics across all packs. */
export function getAllTopics(): string[] {
  return TOPIC_PACKS.flatMap((p) => p.topics)
}

/** Get total topic count across all packs. */
export function getTotalTopicCount(): number {
  return TOPIC_PACKS.reduce((sum, p) => sum + p.topics.length, 0)
}

/** Get a pack by id. */
export function getPackById(id: string): TopicPack | undefined {
  return TOPIC_PACKS.find((p) => p.id === id)
}
