/**
 * ============================================================
 *  Mathematics Formula Encyclopedia — Volume 9
 *  Comprehensive Formula Reference
 *  Chapter 7 — Part 5 (Numerical Methods for PDEs)
 *  Finite Difference Methods,
 *  Stability/Consistency/Convergence & Lax-Richtmyer,
 *  CFL Condition & Von Neumann Analysis,
 *  Finite Element Method (FEM),
 *  Spectral & Pseudospectral Methods,
 *  Multigrid, ADI & Boundary Element Methods,
 *  Worked Problems
 *  Generator for TRIZA
 * ============================================================
 *
 *  Output: data/math-formulas-vol9-ch07p5.json
 * ============================================================
 */
import { writeFileSync, mkdirSync } from 'fs'

interface MathItem {
  question: string
  answer: string
  topic: string
  intent: 'factual_question' | 'how_to' | 'formula_recall' | 'problem_solving'
  keywords: string[]
}

const items: MathItem[] = []

function add(
  question: string,
  answer: string,
  topic: string,
  intent: MathItem['intent'] = 'formula_recall',
  keywords: string[] = []
) {
  items.push({ question, answer, topic, intent, keywords })
}

// ============================================================
// SECTION 1 — FINITE DIFFERENCE METHODS (7 items)
// ============================================================
add(
  'How do you derive finite difference approximations using Taylor series?',
  'Finite difference approximations via Taylor expansion. Forward difference for first derivative: f(x + h) = f(x) + h f\'(x) + h^2/2 f\'\'(x) + h^3/6 f\'\'\'(x) + .... So f\'(x) = (f(x+h) - f(x))/h - h/2 f\'\'(x) + O(h^2). Forward difference: f\'(x) ≈ (f(x+h) - f(x))/h, error O(h) (first-order). Backward: f\'(x) ≈ (f(x) - f(x-h))/h, O(h). Central difference: subtract f(x-h) = f(x) - h f\' + h^2/2 f\'\' - h^3/6 f\'\'\' from f(x+h). (f(x+h) - f(x-h))/(2h) = f\'(x) + h^2/6 f\'\'\'(x) + ... So f\'(x) ≈ (f(x+h) - f(x-h))/(2h), error O(h^2) (second-order; better). Second derivative: add f(x+h) + f(x-h) = 2 f(x) + h^2 f\'\'(x) + h^4/12 f^{(4)}(x) + .... So f\'\'(x) ≈ (f(x+h) - 2 f(x) + f(x-h))/h^2, error O(h^2) (central second difference). Higher-order: use more points (5-point stencil: f\'\' ≈ (-f(x+2h) + 16 f(x+h) - 30 f(x) + 16 f(x-h) - f(x-2h))/(12 h^2), O(h^4)). General: undetermined coefficients. For k-th derivative with n-point stencil, solve linear system for coefficients that cancel lower-order Taylor terms; order = n - k (roughly). Mixed partial: f_{xy} ≈ (f(x+h,y+k) - f(x+h,y-k) - f(x-h,y+k) + f(x-h,y-k))/(4 h k) (central, O(h^2 + k^2)). Non-uniform grid: adjust formulas. Truncation error: leading error term. Round-off: small h amplifies round-off in subtraction; optimal h balances truncation vs round-off (typically h ~ sqrt(eps) for first deriv, eps^{1/3} for second; eps = machine precision ~ 10^{-16}). ✓',
  'ch07p5_fd_taylor',
  'formula_recall',
  ['finite difference', 'Taylor expansion', 'forward backward central', 'truncation error', 'stencil']
)

add(
  'How do you set up the finite difference scheme for the 1D heat equation?',
  'Finite difference for 1D heat equation u_t = alpha u_{xx} on [0, L] with u(0, t) = u(L, t) = 0, u(x, 0) = f(x). Grid: x_j = j Delta x (j = 0, ..., N, Delta x = L/N), t_n = n Delta t. U_j^n ≈ u(x_j, t_n). Discretize: u_t ≈ (U_j^{n+1} - U_j^n)/Delta t (forward Euler in time). u_{xx} ≈ (U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/(Delta x)^2 (central in space). Scheme (Forward Time Central Space, FTCS): (U_j^{n+1} - U_j^n)/Delta t = alpha (U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/(Delta x)^2. So U_j^{n+1} = U_j^n + r (U_{j+1}^n - 2 U_j^n + U_{j-1}^n) where r = alpha Delta t/(Delta x)^2 (Courant number / mesh ratio). Matrix form: U^{n+1} = A U^n where A = I + r T (T = tridiagonal[-1, 2, -1]). With Dirichlet BC: A is (N-1)×(N-1) (interior points). Stability: FTCS is stable iff r <= 1/2 (von Neumann analysis; amplification factor g = 1 - 4 r sin^2(k Delta x/2), |g| <= 1 iff r <= 1/2). So Delta t <= Delta x^2/(2 alpha) (severe restriction: halving Delta x requires quartering Delta t). Backward Euler (BTCS): (U_j^{n+1} - U_j^n)/Delta t = alpha (U_{j+1}^{n+1} - 2 U_j^{n+1} + U_{j-1}^{n+1})/(Delta x)^2. Implicit: U^{n+1} - r T U^{n+1} = U^n, i.e., (I - r T) U^{n+1} = U^n. Solve tridiagonal system each step. Unconditionally stable (any Delta t). Crank-Nicolson: average of FTCS and BTCS: (U_j^{n+1} - U_j^n)/Delta t = (alpha/2) [(U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/(Delta x)^2 + (U_{j+1}^{n+1} - 2 U_j^{n+1} + U_{j-1}^{n+1})/(Delta x)^2]. Implicit, unconditionally stable, second-order in time AND space (O(Delta t^2 + Delta x^2)). ✓',
  'ch07p5_fd_heat_equation',
  'problem_solving',
  ['finite difference', 'heat equation', 'FTCS BTCS', 'Crank-Nicolson', 'Courant number r']
)

add(
  'How do you set up the finite difference scheme for the 1D wave equation?',
  'Finite difference for 1D wave equation u_{tt} = c^2 u_{xx} on [0, L], u(0,t) = u(L,t) = 0, u(x, 0) = f(x), u_t(x, 0) = g(x). Grid: x_j = j Delta x, t_n = n Delta t. Central differences in both: u_{tt} ≈ (U_j^{n+1} - 2 U_j^n + U_j^{n-1})/(Delta t)^2. u_{xx} ≈ (U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/(Delta x)^2. Scheme: (U_j^{n+1} - 2 U_j^n + U_j^{n-1})/(Delta t)^2 = c^2 (U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/(Delta x)^2. Let rho = c Delta t/Delta x (Courant number). U_j^{n+1} = 2 U_j^n - U_j^{n-1} + rho^2 (U_{j+1}^n - 2 U_j^n + U_{j-1}^n). Three-level scheme (needs U^0 and U^1 to start). Initial step U^1 from u(x, 0) = f and u_t(x, 0) = g: U_j^1 = f(x_j) + Delta t g(x_j) + (Delta t^2/2) c^2 f\'\'(x_j) (using Taylor + PDE). Or U_j^1 = f(x_j) + Delta t g(x_j) + (rho^2/2) (f(x_{j+1}) - 2 f(x_j) + f(x_{j-1})) (discretized). Stability (CFL): rho <= 1 (Courant-Friedrichs-Lewy condition). c Delta t <= Delta x (information cannot travel more than one grid point per time step). If rho = 1: exact for traveling waves (U_j^{n+1} = U_{j+1}^n + U_{j-1}^n - U_j^{n-1}, captures F(x+ct) + G(x-ct) exactly). If rho > 1: unstable (amplification grows). Conservation: discrete energy E^n = (1/2) sum [(U_j^{n+1} - U_j^n)^2/Delta t^2 + c^2 (U_{j+1}^n - U_j^n)^2/Delta x^2] Delta x conserved (for rho <= 1). Higher dimensions: u_{tt} = c^2 (u_{xx} + u_{yy}) -> CFL: c Delta t sqrt(1/Delta x^2 + 1/Delta y^2) <= 1. Leapfrog scheme (3-level central). Lax-Wendroff (second-order, adds artificial diffusion term for stability). ✓',
  'ch07p5_fd_wave_equation',
  'problem_solving',
  ['finite difference', 'wave equation', 'three-level scheme', 'CFL condition', 'Courant number rho']
)

add(
  'How do you set up the finite difference scheme for Laplace and Poisson equations?',
  'Finite difference for Laplace Delta u = 0 (or Poisson Delta u = f) on rectangular domain. 2D grid x_i = i Delta x, y_j = j Delta y. 5-point stencil for Laplacian: Delta u ≈ (u_{i+1,j} - 2 u_{i,j} + u_{i-1,j})/Delta x^2 + (u_{i,j+1} - 2 u_{i,j} + u_{i,j-1})/Delta y^2. For Delta x = Delta y = h: Delta u ≈ (u_{i+1,j} + u_{i-1,j} + u_{i,j+1} + u_{i,j-1} - 4 u_{i,j})/h^2 (5-point stencil). Error O(h^2). Poisson: (u_{i+1,j} + u_{i-1,j} + u_{i,j+1} + u_{i,j-1} - 4 u_{i,j})/h^2 = f_{i,j}. Jacobi iteration: u_{i,j}^{(k+1)} = (1/4)(u_{i+1,j}^{(k)} + u_{i-1,j}^{(k)} + u_{i,j+1}^{(k)} + u_{i,j-1}^{(k)} - h^2 f_{i,j}). Gauss-Seidel: use updated values immediately: u_{i,j}^{(k+1)} = (1/4)(u_{i+1,j}^{(k)} + u_{i-1,j}^{(k+1)} + u_{i,j+1}^{(k)} + u_{i,j-1}^{(k+1)} - h^2 f_{i,j}) (faster than Jacobi). SOR (Successive Over-Relaxation): u_{i,j}^{(k+1)} = (1 - omega) u_{i,j}^{(k)} + omega · (Gauss-Seidel update), with omega in (1, 2) (over-relaxation; optimal omega = 2/(1 + sin(pi h)) for square domain, gives O(N) iterations instead of O(N^2) for Jacobi). Convergence: Jacobi and Gauss-Seidel converge for diagonally dominant matrices (Laplacian is). Rate: Jacobi O(N^2) iterations, Gauss-Seidel 2x faster, SOR O(N) with optimal omega. Multigrid: O(N) total work (optimal). Direct solvers: banded Gaussian elimination O(N^3) (prohibitive for large N); sparse LU (O(N^{1.5}) for 2D, O(N^2) for 3D); FFT-based (O(N log N) for separable problems). 9-point stencil: higher accuracy O(h^4) for Laplace (combines 5-point with rotated 5-point). Non-uniform grid: finite volume or box method. Curved boundaries: embedded boundary, immersed boundary, cut-cell methods. ✓',
  'ch07p5_fd_laplace_poisson',
  'problem_solving',
  ['finite difference', 'Laplace Poisson', '5-point stencil', 'Jacobi Gauss-Seidel SOR', 'multigrid']
)

add(
  'What is the Lax-Wendroff scheme for hyperbolic equations?',
  'Lax-Wendroff scheme for advection u_t + a u_x = 0 (a constant). Second-order accurate in space and time. Derivation via Taylor: u(x, t + Delta t) = u + Delta t u_t + (Delta t^2/2) u_{tt} + O(Delta t^3). Use PDE: u_t = -a u_x, u_{tt} = a^2 u_{xx} (from u_t = -a u_x => u_{tt} = -a u_{xt} = -a (u_t)_x = -a (-a u_x)_x = a^2 u_{xx}). So u(x, t + Delta t) = u - a Delta t u_x + (a^2 Delta t^2/2) u_{xx} + .... Discretize: U_j^{n+1} = U_j^n - (a Delta t/(2 Delta x)) (U_{j+1}^n - U_{j-1}^n) + (a^2 Delta t^2/(2 Delta x^2)) (U_{j+1}^n - 2 U_j^n + U_{j-1}^n). Let mu = a Delta t/Delta x (Courant number). U_j^{n+1} = U_j^n - (mu/2)(U_{j+1}^n - U_{j-1}^n) + (mu^2/2)(U_{j+1}^n - 2 U_j^n + U_{j-1}^n). Rewrite: U_j^{n+1} = (mu^2/2 - mu/2) U_{j+1}^n + (1 - mu^2) U_j^n + (mu^2/2 + mu/2) U_{j-1}^n. Stability (von Neumann): |mu| <= 1 (CFL condition; same as upwind). Truncation: O(Delta t^2 + Delta x^2) (second-order). Dissipation: numerical diffusion (a^2 Delta t^2/2 u_{xx} term) damps high frequencies. Dispersion: phase error O(Delta x^2) (Lax-Wendroff is dissipative but dispersive; oscillations behind sharp fronts — Godunov\'s theorem: linear schemes > first-order cannot be monotone for shocks). Two-step Lax-Wendroff (predictor-corrector): U_{j+1/2}^{n+1/2} = (1/2)(U_{j+1}^n + U_j^n) - (Delta t/(2 Delta x)) (F(U_{j+1}^n) - F(U_j^n)) (half-step). U_j^{n+1} = U_j^n - (Delta t/Delta x)(F(U_{j+1/2}^{n+1/2}) - F(U_{j-1/2}^{n+1/2})). For nonlinear conservation u_t + F(u)_x = 0. MacCormack scheme: predictor U*_j = U_j^n - (Delta t/Delta x)(F(U_{j+1}^n) - F(U_j^n)); corrector U_j^{n+1} = (1/2)(U_j^n + U*_j) - (Delta t/(2 Delta x))(F(U*_j) - F(U*_{j-1})). ✓',
  'ch07p5_lax_wendroff',
  'problem_solving',
  ['Lax-Wendroff', 'advection', 'second-order', 'Taylor derivation', 'predictor-corrector']
)

add(
  'What are upwind schemes and why are they used for advection equations?',
  'Upwind schemes for advection u_t + a u_x = 0 (a constant velocity). The flow of information is in the direction of a: if a > 0, information flows from left to right (left is "upwind"); if a < 0, right to left. Upwind discretization uses differencing biased toward the upwind direction. If a > 0: u_x ≈ (U_j^n - U_{j-1}^n)/Delta x (backward difference). Scheme: U_j^{n+1} = U_j^n - (a Delta t/Delta x)(U_j^n - U_{j-1}^n) = U_j^n - mu (U_j^n - U_{j-1}^n) where mu = a Delta t/Delta x. If a < 0: u_x ≈ (U_{j+1}^n - U_j^n)/Delta x (forward difference). Scheme: U_j^{n+1} = U_j^n - mu (U_{j+1}^n - U_j^n). General: U_j^{n+1} = U_j^n - mu (U_j^n - U_{j-1}^n) if a > 0, else U_j^{n+1} = U_j^n - mu (U_{j+1}^n - U_j^n). Stability (von Neumann): amplification g = 1 - mu (1 - e^{-i k Delta x}) for a > 0. |g|^2 = (1 - mu + mu cos(k Delta x))^2 + (mu sin(k Delta x))^2 = 1 - 2 mu (1 - mu) (1 - cos(k Delta x)). |g|^2 <= 1 iff mu (1 - mu) >= 0, i.e., 0 <= mu <= 1 (CFL). So |mu| = |a| Delta t/Delta x <= 1. First-order accurate (O(Delta t + Delta x)). Numerical diffusion: upwind has artificial viscosity nu_art = (|a| Delta x/2)(1 - |mu|) (from modified equation analysis); damps high frequencies (good for stability, bad for sharp fronts). Properties: (1) Monotone (no spurious oscillations; TVD = total variation diminishing). (2) Captures shocks without oscillation (but smears them over ~Delta x). (3) Godunov\'s theorem: linear monotone schemes are at most first-order (can\'t have both high-order and monotone). Nonlinear upwind (MUSCL, WENO, ENO): higher-order where smooth, first-order near shocks (TVD, ENO, WENO reconstructions). Riemann solvers (Godunov, Roe, HLL): exact/approximate Riemann at each cell interface. Flux-limiter (TVD): phi(r) blends first-order (upwind) and second-order (Lax-Wendroff) based on smoothness indicator r. ✓',
  'ch07p5_upwind_schemes',
  'problem_solving',
  ['upwind scheme', 'advection', 'CFL', 'numerical diffusion', 'TVD monotone']
)

add(
  'How do you handle boundary conditions in finite difference methods?',
  'Boundary conditions in FD methods. Dirichlet (u specified on boundary): simply set U_j^n = g(x_j, t_n) at boundary grid points (rows of the system removed; RHS adjusted). For 1D heat eq on [0, L] with u(0, t) = g_0, u(L, t) = g_L: U_0^n = g_0(t_n), U_N^n = g_L(t_n); interior points j = 1, ..., N-1 solved by the scheme. Neumann (partial u/partial n specified): use ghost points or one-sided differences. Ghost point method: introduce U_{-1} (fictitious point outside). partial u/partial x(0, t) = h => (U_1 - U_{-1})/(2 Delta x) = h (central at boundary) => U_{-1} = U_1 - 2 Delta x · h. Substitute into the scheme at j = 0. Or one-sided: (U_1 - U_0)/Delta x = h (forward, first-order); (3 U_0 - 4 U_1 + U_2)/(2 Delta x) = h (second-order one-sided). Robin (a u + b partial u/partial n = g): combine the above; e.g., a U_0 + b (U_1 - U_{-1})/(2 Delta x) = g, solve for U_{-1}. Time-dependent BC: update at each time step. Curved boundary (non-grid-aligned): immersed boundary method (force term at boundary), cut-cell (reshape cells near boundary), embedded boundary (modify stencil near boundary). Higher-order BC: use one-sided stencils of matching order. Compatibility at corners: for smooth solution, BC and IC must agree at corner (e.g., f(0) = g_0(0)); else corner singularity. Periodic BC: U_0 = U_N (wrap around); use circular tridiagonal solver. Outflow / radiation BC: absorbing (partial u/partial t + c partial u/partial x = 0 at outflow), perfectly matched layers (PML), sponge layers. Nonlocal BC (fractional Laplacian): special techniques (integral over boundary, fast multipole). Adaptive mesh refinement (AMR): grid refinement near boundaries/features (Berger-Oliger, block-structured). ✓',
  'ch07p5_fd_boundary_conditions',
  'formula_recall',
  ['boundary conditions FD', 'Dirichlet Neumann Robin', 'ghost point', 'one-sided difference', 'immersed boundary']
)

// ============================================================
// SECTION 2 — STABILITY/CONSISTENCY/CONVERGENCE & LAX-RICHTMYER (6 items)
// ============================================================
add(
  'What is the Lax-Richtmyer equivalence theorem for finite difference schemes?',
  'Lax-Richtmyer equivalence theorem (1956). For a well-posed linear initial value problem (IVP) and a consistent finite difference scheme, the scheme is CONVERGENT if and only if it is STABLE. Statement: let the PDE be u_t = L u with u(0) = f (well-posed: ||u(t)|| <= C e^{a t} ||f||), discretized as U^{n+1} = C(Delta t, Delta x) U^n (one-step scheme; or multi-step). Consistency: C(Delta t, Delta x) -> e^{Delta t L} as Delta t, Delta x -> 0 (local truncation error tau = (C(Delta t) u(t_n) - u(t_{n+1}))/Delta t -> 0). Stability: ||C(Delta t)^n|| <= K e^{a T} for all n Delta t <= T (uniform bound on powers; equivalently, amplification operator bounded). Then: convergence ||U^n - u(t_n)|| -> 0 as Delta t -> 0 iff stability holds. Convergence rate = order of consistency (e.g., O(Delta t^p + Delta x^q) consistent + stable => O(Delta t^p + Delta x^q) convergent). Significance: reduces convergence (hard to prove directly) to stability + consistency (easier). Foundation of numerical PDE theory. Caveats: (1) Linear only (nonlinear needs separate analysis; often linearize + stability of linearized). (2) IVP (initial value); BVP (boundary value) has separate theory. (3) Requires well-posedness of PDE. Generalizations: Kreiss matrix theorem (stability equivalences), Gustafsson-Sundqvist-Kreiss (boundary stability), Strang theorem (nonlinear). For nonlinear hyperbolic (conservation laws): convergence theory harder (TVD, ENO, WENO; convergence to entropy solution; Bressan, Bressan-LeFloch). For elliptic BVP: equivalence via coercivity (Lax-Milgram) + Galerkin convergence (Cea\'s lemma). ✓',
  'ch07p5_lax_richtmyer',
  'formula_recall',
  ['Lax-Richtmyer', 'equivalence theorem', 'consistency stability convergence', 'linear IVP', 'well-posed']
)

add(
  'What is consistency of a finite difference scheme and how do you check it?',
  'Consistency of a finite difference scheme. Definition: a scheme U^{n+1} = Q(Delta t, Delta x) U^n approximating u_t = L u is consistent if the local truncation error tau = (Q(Delta t) u(t_n) - u(t_{n+1}))/Delta t -> 0 as Delta t, Delta x -> 0 (when u is a smooth exact solution of the PDE). Equivalently: substitute the exact PDE solution u into the scheme; the residual (after dividing by Delta t) goes to zero. Order of accuracy: scheme is order (p, q) if tau = O(Delta t^p + Delta x^q). Example: FTCS for heat eq u_t = alpha u_{xx}. Scheme: (U_j^{n+1} - U_j^n)/Delta t = alpha (U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/Delta x^2. Substitute exact u: tau = (u_j^{n+1} - u_j^n)/Delta t - alpha (u_{j+1}^n - 2 u_j^n + u_{j-1}^n)/Delta x^2. Taylor: u_j^{n+1} = u + Delta t u_t + (Delta t^2/2) u_{tt} + ..., u_{j+1}^n = u + Delta x u_x + (Delta x^2/2) u_{xx} + (Delta x^3/6) u_{xxx} + (Delta x^4/24) u_{xxxx} + .... So (u_j^{n+1} - u_j^n)/Delta t = u_t + (Delta t/2) u_{tt} + O(Delta t^2). And (u_{j+1} - 2 u_j + u_{j-1})/Delta x^2 = u_{xx} + (Delta x^2/12) u_{xxxx} + O(Delta x^4). So tau = u_t + (Delta t/2) u_{tt} - alpha u_{xx} - alpha (Delta x^2/12) u_{xxxx} + ... = (Delta t/2) u_{tt} - (alpha Delta x^2/12) u_{xxxx} + ... (using PDE u_t = alpha u_{xx}). So tau = O(Delta t + Delta x^2): FTCS is first-order in time, second-order in space. Crank-Nicolson: O(Delta t^2 + Delta x^2) (second-order both). Check: substitute, Taylor expand, collect leading error terms. Lax-Wendroff: O(Delta t^2 + Delta x^2) (designed by including Delta t^2 correction). Consistency is necessary but not sufficient for convergence (need stability; Lax-Richtmyer). ✓',
  'ch07p5_consistency_check',
  'formula_recall',
  ['consistency', 'local truncation error', 'Taylor expansion', 'order of accuracy', 'substitute exact solution']
)

add(
  'What is stability of a finite difference scheme and how is it analyzed?',
  'Stability of a finite difference scheme. Definition: a one-step scheme U^{n+1} = Q(Delta t) U^n is stable if there exist constants K > 0 and a such that ||Q(Delta t)^n|| <= K e^{a T} for all n with n Delta t <= T (uniform bound on powers of Q, independent of Delta t). Equivalently: small perturbations in initial data do not grow unboundedly (in finite time T). Types: (1) Zero-stability (fixed Delta t, n -> inf with T fixed). (2) Absolute stability (specific Delta t, all n). (3) Lax-Richtmyer stability (uniform over Delta t -> 0). Methods to check stability: (a) Von Neumann (Fourier) analysis: assume U_j^n = g^n e^{i k j Delta x}, derive amplification factor g(k). Scheme stable iff |g(k)| <= 1 + C Delta t for all k (von Neumann condition). Works for constant-coefficient schemes on infinite/uniform grid. (b) Matrix method: write U^{n+1} = A U^n, check ||A^n|| <= K (eigenvalue: |lambda_max(A)| <= 1 + C Delta t; for normal A, sufficient; for non-normal, need pseudospectrum). (c) Energy method: define discrete energy E^n, show E^{n+1} <= E^n (or <= (1 + C Delta t) E^n). Works for variable coefficients, nonlinear. (d) CFL condition (necessary, not sufficient): information propagation speed in scheme >= PDE speed (Courant-Friedrichs-Lewy). Examples: FTCS heat eq: |g| = |1 - 4 r sin^2(k Delta x/2)| <= 1 iff r <= 1/2 (stable). Upwind advection: |g|^2 = 1 - 2 mu (1 - mu)(1 - cos(k Delta x)) <= 1 iff 0 <= mu <= 1 (CFL). Crank-Nicolson: |g| = |(1 - 2 r sin^2/2)/(1 + 2 r sin^2/2)| <= 1 for all r (unconditionally stable). Backward Euler heat: |g| = |1/(1 + 4 r sin^2/2)| <= 1 (unconditionally stable). Strict vs practical stability: |g| <= 1 (strict); |g| <= 1 + C Delta t (practical, sufficient for Lax-Richtmyer). ✓',
  'ch07p5_stability_analysis',
  'formula_recall',
  ['stability', 'amplification factor', 'von Neumann', 'energy method', 'CFL necessary']
)

add(
  'What is the von Neumann stability analysis and how do you apply it?',
  'Von Neumann (Fourier) stability analysis. Setup: linear constant-coefficient finite difference scheme on uniform grid, infinite or periodic domain. Ansatz: U_j^n = g^n e^{i k j Delta x} (Fourier mode with wavenumber k, amplification factor g per time step). Substitute into scheme; solve for g as function of k, Delta t, Delta x. Stability: |g(k)| <= 1 + C Delta t for all k in the resolved range (|k| <= pi/Delta x by Nyquist) — von Neumann condition. (For Delta t -> 0, this becomes |g| <= 1.) Example 1 (FTCS heat): (U_j^{n+1} - U_j^n)/Delta t = alpha (U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/Delta x^2. Substitute U_j^n = g^n e^{i k j Delta x}: g - 1 = r (e^{i k Delta x} - 2 + e^{-i k Delta x}) = r (2 cos(k Delta x) - 2) = -4 r sin^2(k Delta x/2). So g = 1 - 4 r sin^2(k Delta x/2). |g| <= 1 iff 0 <= 4 r sin^2 <= 2 (since 1 - x >= -1 requires x <= 2, and 1 - x <= 1 requires x >= 0). Max of sin^2 is 1, so 4 r <= 2, r <= 1/2. Stable iff r = alpha Delta t/Delta x^2 <= 1/2. Example 2 (upwind advection u_t + a u_x = 0, a > 0): U_j^{n+1} = U_j^n - mu (U_j^n - U_{j-1}^n), mu = a Delta t/Delta x. g = 1 - mu (1 - e^{-i k Delta x}) = 1 - mu + mu (cos(k Delta x) - i sin(k Delta x)). |g|^2 = (1 - mu + mu cos)^2 + mu^2 sin^2 = (1 - mu)^2 + 2 mu (1 - mu) cos + mu^2 = 1 - 2 mu + 2 mu^2 + 2 mu (1 - mu) cos. = 1 - 2 mu (1 - mu) (1 - cos). Max at cos = -1: |g|^2 = 1 - 4 mu (1 - mu) <= 1 iff mu (1 - mu) >= 0, i.e., 0 <= mu <= 1. So CFL |mu| <= 1. Example 3 (Crank-Nicolson heat): g = (1 - 2 r sin^2/2)/(1 + 2 r sin^2/2), |g| <= 1 always (numerator smaller than denominator in abs). Unconditionally stable. Limitations: only for linear constant-coefficient on uniform grid; for variable coefficients or nonlinear, use energy method or freeze coefficients (heuristic). ✓',
  'ch07p5_von_neumann_analysis',
  'problem_solving',
  ['von Neumann', 'Fourier stability', 'amplification factor', 'FTCS upwind Crank-Nicolson', 'CFL']
)

add(
  'What is the CFL (Courant-Friedrichs-Lewy) condition?',
  'CFL condition (Courant-Friedrichs-Lewy, 1928). Necessary condition for convergence of a finite difference scheme for a PDE: the domain of dependence of the numerical scheme (at a grid point) must CONTAIN the domain of dependence of the PDE. PDE domain of dependence: for hyperbolic PDE (wave eq, advection), the set of initial data points that influence u(x_0, t_0). For advection u_t + a u_x = 0: a single characteristic x - a t = const, so domain of dependence of (x_0, t_0) is the single point x_0 - a t_0 (on t = 0). For wave u_{tt} = c^2 u_{xx}: interval [x_0 - c t_0, x_0 + c t_0] (characteristic cone). Numerical domain of dependence: set of grid points at t = 0 that influence U(x_0, t_0) via the scheme. For upwind advection: U_j^{n+1} = U_j^n - mu (U_j^n - U_{j-1}^n); each step looks at j and j-1. After n steps (t_0 = n Delta t), the influence comes from grid points x_{j-n} to x_j, i.e., x_0 - n Delta x = x_0 - (t_0/Delta t) Delta x to x_0. PDE domain: x_0 - a t_0. CFL: x_0 - a t_0 in [x_0 - n Delta x, x_0], i.e., a t_0 <= n Delta x = (t_0/Delta t) Delta x, i.e., a Delta t <= Delta x, i.e., mu = a Delta t/Delta x <= 1. For a < 0: similar, |a| Delta t <= Delta x. Wave eq 1D: c Delta t/Delta x <= 1 (rho <= 1). 2D wave: c Delta t sqrt(1/Delta x^2 + 1/Delta y^2) <= 1. Heat eq (parabolic): infinite PDE propagation speed, so CFL is automatically satisfied for any Delta t (the necessary condition is trivially true; actual stability requires stronger condition like r <= 1/2 for FTCS). CFL is NECESSARY but NOT SUFFICIENT (e.g., FTCS heat satisfies CFL trivially but unstable for r > 1/2). For hyperbolic: CFL usually also sufficient for linear schemes (with von Neumann). Physical interpretation: numerical scheme must propagate information at least as fast as PDE; if scheme too slow (Delta t too large for given Delta x), it can\'t "see" the relevant initial data, and can\'t converge. Generalization: CFL for systems (max eigenvalue), for nonlinear (freeze coefficients), for FEM (element-wise CFL). ✓',
  'ch07p5_cfl_condition',
  'formula_recall',
  ['CFL', 'Courant-Friedrichs-Lewy', 'domain of dependence', 'necessary condition', 'hyperbolic PDE']
)

add(
  'What is the modified equation analysis for finite difference schemes?',
  'Modified equation analysis (Warming-Hyett 1974). Idea: the finite difference scheme is an EXACT solution to a MODIFIED PDE (the PDE that the scheme solves exactly), which differs from the original PDE by truncation terms. Analysis: derive the modified PDE by substituting Taylor expansion (assuming smooth solution) and eliminating time derivatives using the PDE itself. Example: upwind scheme for u_t + a u_x = 0, U_j^{n+1} = U_j^n - mu (U_j^n - U_{j-1}^n). Substitute smooth u: u + Delta t u_t + (Delta t^2/2) u_{tt} + ... = u - mu (u - (u - Delta x u_x + Delta x^2/2 u_{xx} - ...)) = u - mu (Delta x u_x - Delta x^2/2 u_{xx} + Delta x^3/6 u_{xxx} - ...). Use mu = a Delta t/Delta x. Divide by Delta t: u_t + (Delta t/2) u_{tt} + ... = -a u_x + (a Delta x/2) u_{xx} - (a Delta x^2/6) u_{xxx} + .... Eliminate u_{tt} = -a u_{xt} = a^2 u_{xx} (using PDE u_t = -a u_x; at lowest order). So u_t + (Delta t/2) a^2 u_{xx} + ... = -a u_x + (a Delta x/2) u_{xx} + .... Rearrange: u_t + a u_x = (a Delta x/2 - a^2 Delta t/2) u_{xx} + ... = (a Delta x/2)(1 - mu) u_{xx} + higher-order. Modified equation: u_t + a u_x = (a Delta x/2)(1 - mu) u_{xx} + O(Delta x^2, Delta t^2). The upwind scheme is a first-order accurate solver of u_t + a u_x = (a Delta x/2)(1 - mu) u_{xx} (advection-diffusion with artificial viscosity nu = (a Delta x/2)(1 - mu) >= 0 for 0 <= mu <= 1). This explains: (1) Upwind is stable (artificial diffusion damps high frequencies). (2) Upwind smears shocks (diffusive). (3) mu = 1 gives zero diffusion (exact for pure advection). Lax-Wendroff modified eq: u_t + a u_x = -(a Delta x^2/6)(1 - mu^2) u_{xxx} + ... (dispersive, third-derivative; causes phase errors, oscillations behind shocks). Lax-Friedrichs: stronger artificial diffusion. Applications: (a) Understand numerical behavior (diffusion vs dispersion). (b) Design schemes (add counter-diffusion for anti-diffusive corrections; flux-limiter). (c) Stability: artificial viscosity >= 0 implies stability. (d) Convergence: scheme converges to modified PDE; modified PDE -> original as Delta x -> 0 (consistency). ✓',
  'ch07p5_modified_equation',
  'formula_recall',
  ['modified equation', 'Warming-Hyett', 'artificial viscosity', 'numerical diffusion', 'dispersion error']
)

// ============================================================
// SECTION 3 — FINITE ELEMENT METHOD (7 items)
// ============================================================
add(
  'What is the weak formulation of an elliptic PDE for the finite element method?',
  'Weak formulation for FEM. Consider -div(A grad u) + c u = F in D, u = g_D on ∂D_D (Dirichlet), (A grad u) · n = g_N on ∂D_N (Neumann). Multiply by test function v and integrate: integral_D [-div(A grad u) + c u] v dx = integral_D F v dx. Integrate by parts (Green\'s identity): integral_D (A grad u · grad v + c u v) dx - integral_{∂D} (A grad u · n) v dS = integral_D F v dx. Apply BC: on ∂D_D, v = 0 (test functions vanish on Dirichlet part); on ∂D_N, (A grad u) · n = g_N. So: integral_D (A grad u · grad v + c u v) dx = integral_D F v dx + integral_{∂D_N} g_N v dS. Define bilinear form a(u, v) = integral_D (A grad u · grad v + c u v) dx and linear functional L(v) = integral_D F v dx + integral_{∂D_N} g_N v dS. Weak form: find u in H^1_g(D) (functions with u = g_D on ∂D_D) such that a(u, v) = L(v) for all v in V = H^1_0(D) (test functions vanishing on ∂D_D). Existence/uniqueness: Lax-Milgram (a bounded + coercive, L bounded). FEM discretization: choose finite-dimensional subspace V_h ⊂ V (piecewise polynomial on triangulation). Find u_h in V_h (with u_h = g_D interpolated on ∂D_D) such that a(u_h, v_h) = L(v_h) for all v_h in V_h (Galerkin method). Matrix form: A U = b, A_{ij} = a(phi_j, phi_i), b_i = L(phi_i), where {phi_i} basis of V_h. Cea\'s lemma: ||u - u_h||_{H^1} <= (C_1/C_2) inf_{v_h in V_h} ||u - v_h||_{H^1} (quasi-optimality; FEM is best approximation up to constants). ✓',
  'ch07p5_fem_weak_formulation',
  'formula_recall',
  ['weak formulation', 'FEM', 'bilinear form', 'test function', 'Galerkin method']
)

add(
  'How do you construct piecewise linear finite element basis functions?',
  'Piecewise linear FEM basis functions in 1D and 2D. 1D: domain [a, b] triangulated into elements [x_{i-1}, x_i] (nodes x_i). Hat function phi_i(x): piecewise linear, phi_i(x_i) = 1, phi_i(x_j) = 0 for j != i. Explicit: phi_i(x) = (x - x_{i-1})/(x_i - x_{i-1}) for x in [x_{i-1}, x_i]; (x_{i+1} - x)/(x_{i+1} - x_i) for x in [x_i, x_{i+1}]; 0 otherwise. Support: [x_{i-1}, x_{i+1}] (two elements). Properties: (1) Partition of unity: sum_i phi_i = 1. (2) Local support (sparse matrices). (3) Continuous across element boundaries (C^0). (4) Derivative is piecewise constant (discontinuous at nodes). 2D: triangulation (mesh of triangles). Hat function phi_i at vertex i: phi_i = 1 at vertex i, 0 at all other vertices, linear on each triangle. On triangle with vertices (i, j, k), use barycentric coordinates (lambda_i, lambda_j, lambda_k) with lambda_i + lambda_j + lambda_k = 1; phi_i = lambda_i on this triangle. Barycentric: lambda_i = Area(sub-triangle opposite i)/Area(triangle). For triangle (x_1, y_1), (x_2, y_2), (x_3, y_3): lambda_i = (1/(2A)) [ (x_j y_k - x_k y_j) + (y_j - y_k) x + (x_k - x_j) y ] where A = triangle area, {i, j, k} cyclic. Properties same as 1D. Stiffness matrix A_{ij} = integral grad phi_i · grad phi_j dx (sparse, banded for local support). Element stiffness matrix (on one triangle, linear elements): A^{elem}_{ij} = integral_{triangle} grad lambda_i · grad lambda_j dx = (1/(4A)) [ (x_k - x_j)(x_k - x_i) + (y_k - y_j)(y_k - y_i) ] · A (wait, formula): A^{elem}_{ij} = (b_i b_j + c_i c_j)/(4 A) where b_i = y_j - y_k, c_i = x_k - x_j (cyclic), A = triangle area. Local-to-global assembly: loop over elements, compute local matrix, add to global. Mass matrix M_{ij} = integral phi_i phi_j dx (for time-dependent / eigenvalue problems). Element mass (linear triangle): M^{elem} = (A/12) [[2, 1, 1], [1, 2, 1], [1, 1, 2]] (lumped: A/3 on diagonal). ✓',
  'ch07p5_fem_basis_functions',
  'problem_solving',
  ['FEM basis', 'hat function', 'piecewise linear', 'barycentric coordinates', 'stiffness mass matrix']
)

add(
  'What is the Galerkin method and Cea\'s lemma for FEM convergence?',
  'Galerkin method and Cea\'s lemma. Setup: weak form a(u, v) = L(v) for all v in V (Hilbert space), u in H^1_g. Galerkin: choose finite-dim subspace V_h ⊂ V (e.g., piecewise polynomial on mesh), find u_h in V_h (or affine space V_h + g_h) such that a(u_h, v_h) = L(v_h) for all v_h in V_h. Matrix form: A U = b, A_{ij} = a(phi_j, phi_i), b_i = L(phi_i). Symmetric A if a symmetric. Cea\'s lemma: if a is bounded (|a(u, v)| <= C_1 ||u|| ||v||) and coercive (a(u, u) >= C_2 ||u||^2), then ||u - u_h||_V <= (C_1/C_2) inf_{v_h in V_h} ||u - v_h||_V. Proof: u - u_h = (u - v_h) + (v_h - u_h). Galerin orthogonality: a(u - u_h, v_h) = 0 (since a(u, v_h) = L(v_h) = a(u_h, v_h)). Coercivity of a on u - u_h: C_2 ||u - u_h||^2 <= a(u - u_h, u - u_h) = a(u - u_h, u - v_h) (using Galerkin orthogonality with v_h = u_h - ... wait, v_h - u_h is in V_h so a(u - u_h, v_h - u_h) = 0; so a(u - u_h, u - u_h) = a(u - u_h, u - v_h) + a(u - u_h, v_h - u_h) = a(u - u_h, u - v_h) + 0). Then |a(u - u_h, u - v_h)| <= C_1 ||u - u_h|| ||u - v_h||. So C_2 ||u - u_h||^2 <= C_1 ||u - u_h|| ||u - v_h||, divide: ||u - u_h|| <= (C_1/C_2) ||u - v_h||. Take inf over v_h. ✓ Convergence: if V_h approximates V (interpolation error -> 0), then u_h -> u. Rate: ||u - u_h||_{H^1} <= C h^p ||u||_{H^{p+1}} where p = polynomial degree (p=1 linear: O(h); p=2 quadratic: O(h^2)). L^2 error (Nitsche\'s trick): ||u - u_h||_{L^2} <= C h^{p+1} ||u||_{H^{p+1}} (one order better than H^1). p-refinement (increase polynomial degree), h-refinement (decrease mesh size), hp-FEM (combine). ✓',
  'ch07p5_galerkin_cea_lemma',
  'formula_recall',
  ['Galerkin', 'Cea\'s lemma', 'quasi-optimality', 'interpolation error', 'Nitsche trick']
)

add(
  'How do you derive the error estimates for the finite element method?',
  'FEM error estimates. Setup: weak form, Galerkin FEM with piecewise polynomial degree p on mesh size h. H^1 error (Cea + interpolation): ||u - u_h||_{H^1} <= (C_1/C_2) inf ||u - v_h|| <= C ||u - I_h u||_{H^1} where I_h u is the interpolant. Interpolation error (Bramble-Hilbert lemma): ||u - I_h u||_{H^1} <= C h^p |u|_{H^{p+1}} (p-th degree polynomial interpolates; |·|_{H^{p+1}} = seminorm = L^2 norm of (p+1)-th derivatives). So ||u - u_h||_{H^1} <= C h^p |u|_{H^{p+1}}. L^2 error (Nitsche\'s duality / Aubin-Nitsche trick): solve dual problem a(w, v) = (u - u_h, v)_{L^2} for all v (with appropriate BC). Then ||u - u_h||_{L^2}^2 = a(u - u_h, w) = a(u - u_h, w - I_h w) (Galerkin orthogonality) <= C_1 ||u - u_h||_{H^1} ||w - I_h w||_{H^1} <= C ||u - u_h||_{H^1} · h ||w||_{H^2} (assuming H^2 regularity of dual: ||w||_{H^2} <= C ||u - u_h||_{L^2}). So ||u - u_h||_{L^2}^2 <= C h^{p+1} |u|_{H^{p+1}} ||u - u_h||_{L^2}, divide: ||u - u_h||_{L^2} <= C h^{p+1} |u|_{H^{p+1}}. One order better than H^1. H^{-s} negative norm: even better (duality iterates). L^inf error (De Giorgi-Nash-Moser style): ||u - u_h||_{L^inf} <= C h^{p+1} |log h|^{alpha} |u|_{W^{p+1, inf}} (with log factor in 2D; sharp). Derivative recovery (Zienkiewicz-Zhu patch recovery): superconvergent post-processing, O(h^{p+1}) gradient at patch centers. A priori vs a posteriori: a priori needs smoothness (|u|_{H^{p+1}}); a posteriori uses residual ||h^2 (F - L u_h)|| (Babuska-Rheinboldt, Kelly-Gago, ZZ) for adaptive refinement. Adaptive FEM loop: SOLVE -> ESTIMATE -> MARK -> REFINE. Convergence of AFEM (Cascon-Kreuzer-Nochetto-Siebert): optimal rate O(N^{-p/d}) in energy norm. Locking (incompressibility, thin structures): mixed FEM (Taylor-Hood, MINI), stabilized FEM. ✓',
  'ch07p5_fem_error_estimates',
  'formula_recall',
  ['FEM error', 'Bramble-Hilbert', 'Nitsche duality', 'L^2 H^1 error', 'adaptive FEM']
)

add(
  'What are higher-order and spectral finite element methods?',
  'Higher-order and spectral FEM. p-FEM: increase polynomial degree p on fixed mesh. Convergence: exponential for analytic solution (||u - u_h|| <= C exp(-b p^{1/(n+1)}) ||u||). h-p FEM: combine h-refinement and p-refinement (Babuska-Szabo). Exponential convergence for piecewise-analytic solution with geometric mesh refinement near singularities. Spectral methods: global polynomial basis (Chebyshev, Legendre, Fourier) on whole domain (or simple elements). Exponential convergence for smooth/analytic solution (||u - u_N|| <= C e^{-sigma N} ||u||, where N = spectral degree). Chebyshev collocation: basis T_k(x) (Chebyshev polynomials), collocation at Chebyshev-Gauss-Lobatto points x_j = cos(j pi/N). Derivative matrices dense (global coupling). Fourier spectral: for periodic BC, basis e^{i k x}, derivative = i k (diagonal in Fourier); pseudo-spectral: compute nonlinear terms in physical space (FFT), derivatives in Fourier (FFT back). Legendre-Galerkin: basis L_k(x) (Legendre polynomials); stiffness matrix tridiagonal (after basis transform). Spectral element: hybrid (high-order on elements, tensor-product structure). Hp-Galerkin: FEM with hp-discretization. Comparison: FD/FEM: algebraic convergence (h^p), local. Spectral: exponential (e^{-N}), global. p-FEM: between. Choose based on solution smoothness (smooth -> spectral; rough -> low-order FEM). Computational cost: spectral dense matrices O(N^3) direct, O(N log N) FFT; FEM sparse O(N) multigrid. Stability: CFL for spectral time-stepping: Delta t ~ O(N^{-2}) or O(N^{-1}) (more restrictive than FEM). Applications: turbulence (spectral DNS), weather/climate (spectral element), quantum chemistry (spectral), electromagnetics (hp-FEM for scattering). Nodal vs modal: nodal (Lagrange interpolation at nodes) vs modal (orthogonal polynomial basis). Discontinuous Galerkin (DG): elements with discontinuous basis, fluxes across interfaces (interior penalty, LDG, HDG). High-order, parallelizable, hp-adaptive. ✓',
  'ch07p5_higher_order_spectral_fem',
  'formula_recall',
  ['p-FEM', 'spectral method', 'exponential convergence', 'Chebyshev Legendre', 'hp-FEM DG']
)

add(
  'How do you solve the time-dependent heat equation using FEM?',
  'FEM for time-dependent heat equation u_t - div(A grad u) = F in D × (0, T], u = 0 on ∂D, u(x, 0) = u_0(x). Weak form: find u(t) in H^1_0(D) such that (u_t, v) + a(u, v) = (F, v) for all v in H^1_0, with u(0) = u_0. Here a(u, v) = integral A grad u · grad v (bilinear), (·, ·) = L^2 inner product. Spatial discretization: u_h(x, t) = sum_j U_j(t) phi_j(x) (phi_j FEM basis). Galerkin: (u_{h,t}, phi_i) + a(u_h, phi_i) = (F, phi_i) for all i. Matrix form: M U\'(t) + K U(t) = F(t), where M_{ij} = (phi_j, phi_i) (mass matrix), K_{ij} = a(phi_j, phi_i) (stiffness), F_i = (F, phi_i). System of ODEs (M U\' + K U = F). Time discretization: Theta-method: M (U^{n+1} - U^n)/Delta t + K (theta U^{n+1} + (1-theta) U^n) = theta F^{n+1} + (1-theta) F^n. theta = 0: forward Euler (explicit, M U^{n+1} = M U^n - Delta t K U^n + Delta t F^n; solve with mass matrix, conditionally stable, Delta t <= C h^2). theta = 1: backward Euler (implicit, (M + Delta t K) U^{n+1} = M U^n + Delta t F^{n+1}; solve with stiffness+mass, unconditionally stable, first-order). theta = 1/2: Crank-Nicolson (implicit, second-order, unconditionally stable; (M + Delta t/2 K) U^{n+1} = (M - Delta t/2 K) U^n + ...). Stability (von Neumann for FEM): lumped mass (M diagonal) gives standard CFL r <= 1/6 (linear elements); consistent mass has milder restriction. Higher-order time: BDF (backward differentiation formula, order 2-6), Runge-Kutta (explicit RK4, implicit SDIRK), IMEX (implicit for stiff, explicit for non-stiff). Adaptive time: error estimator (Richter), step size control. Space-time FEM: discretize space and time together (multiscale). Mass lumping: replace M by diagonal (row-sum); avoids solving mass system, but reduces accuracy (first-order time) and changes stability. ✓',
  'ch07p5_fem_heat_time',
  'problem_solving',
  ['FEM heat', 'time-dependent', 'mass stiffness matrix', 'theta-method', 'Crank-Nicolson FEM']
)

add(
  'What is the discontinuous Galerkin (DG) method?',
  'Discontinuous Galerkin (DG) method. Idea: FEM with DISCONTINUOUS basis functions across element boundaries; continuity enforced weakly via numerical fluxes. Setup: conservation law u_t + div F(u) = 0 (or elliptic -div(A grad u) = f). Triangulation T_h. On each element K, u_h is polynomial (degree p), independent across elements (no continuity at ∂K). Weak form (per element): integral_K (u_t phi - F(u) · grad phi) dx + integral_{∂K} F_hat · n phi dS = 0 for all phi in P_p(K). F_hat = numerical flux at element boundary (depends on u_h from inside K and outside K, i.e., from neighbor). Choices of F_hat: (1) Godunov flux (exact Riemann solver; upwind for advection). (2) Roe flux (approximate Riemann). (3) Lax-Friedrichs: F_hat = (1/2)(F(u_L) + F(u_R)) - (alpha/2)(u_R - u_L) (alpha = max |F\'(u)|; dissipative). (4) Engquist-Osher. (5) HLL, HLLC. For elliptic: interior penalty (IP) method: add penalty term sigma/h [u] [v] on edges to enforce continuity; bilinear form a_h(u, v) = sum_K integral grad u · grad v + sum_edges [penalty + consistency]. LDG (Local DG): write elliptic as first-order system (grad u = q, div q = f), use mixed FEM with DG. HDG (Hybridizable DG): introduce trace unknowns on edges, eliminate element unknowns locally, solve smaller global system for traces. Properties: (1) High-order accuracy (hp-adaptive). (2) Local conservation (flux form). (3) Parallelizable (compact stencil after static condensation). (4) Handles complex geometry, hanging nodes, non-conforming meshes. (5) Stable for convection-dominated (upwind). (6) More DOFs than continuous FEM (each element has its own copy of boundary DOFs). Error estimates: ||u - u_h||_{L^2} <= C h^{p+1} ||u||_{H^{p+1}} (one order better than interior Galerkin with same p). Energy: ||u - u_h||_{H^1} <= C h^p. DG for time-dependent hyperbolic: RKDG (Cockburn-Shu): DG in space + explicit Runge-Kutta (TVD-RK) in time. Stability: CFL Delta t <= C h/(max|F\'|·(2p+1)) (CFL shrinks with p). Applications: compressible flow, electromagnetics (Maxwell DG), transport, neutron transport, shallow water, weather. ✓',
  'ch07p5_discontinuous_galerkin',
  'formula_recall',
  ['discontinuous Galerkin', 'DG', 'numerical flux', 'interior penalty', 'LDG HDG']
)

// ============================================================
// SECTION 4 — SPECTRAL & PSEUDOSPECTRAL METHODS (5 items)
// ============================================================
add(
  'What is the Fourier spectral method for PDEs with periodic boundary conditions?',
  'Fourier spectral method. For periodic BC on [0, 2 pi] (or torus T^n). Approximate u(x) ≈ u_N(x) = sum_{k = -N/2}^{N/2} hat u_k e^{i k x} (truncated Fourier series). Derivatives: du/dx ≈ sum i k hat u_k e^{i k x} (multiply by i k in Fourier; exact for spectral accuracy). PDE u_t = L u: in Fourier, hat u_k\'(t) = L_k hat u_k(t) (decoupled ODEs; for linear L). Solve each ODE. Nonlinear: pseudo-spectral (compute nonlinear term in physical space). Pseudospectral (collocation): (1) Represent u on grid x_j = 2 pi j/N (j = 0, ..., N-1). (2) Compute u(x_j) (function values). (3) FFT to get hat u_k. (4) Multiply by (ik)^m for m-th derivative. (5) Inverse FFT to get derivative values at grid. (6) Compute nonlinear term at grid points (no aliasing if dealiased; 2/3 rule: zero out top 1/3 modes). Time-stepping: RK4, IMEX (implicit for stiff linear, explicit for non-stiff nonlinear). Stability: explicit time step Delta t <= C/N^2 (CFL for diffusion; spectral makes Delta x ~ 1/N, so Delta t ~ 1/N^2); for advection: Delta t <= C/N. Aliasing: nonlinear product in physical space creates modes beyond N (alias back into [-N/2, N/2]); dealias by zero-padding (2/3 rule: keep modes |k| <= N/3, zero rest). Convergence: exponential (||u - u_N|| <= C e^{-sigma N} ||u||) for analytic u; algebraic (||u - u_N|| ~ N^{-s}) for u in H^s. Spectral accuracy: error decreases faster than any polynomial for C^inf data. Advantages: extreme accuracy for smooth solutions, low numerical diffusion/dispersion. Disadvantages: requires smooth solution and simple geometry (periodic or tensor-product). Applications: turbulence DNS (incompressible Navier-Stokes), weather/climate (spectral transform method), plasma physics, quantum mechanics (Bose-Einstein condensate via Gross-Pitaevskii), nonlinear waves. Non-periodic: Chebyshev or Legendre spectral (next item). ✓',
  'ch07p5_fourier_spectral',
  'formula_recall',
  ['Fourier spectral', 'pseudospectral', 'FFT', 'periodic BC', 'exponential convergence']
)

add(
  'What is the Chebyshev spectral method for non-periodic boundary value problems?',
  'Chebyshev spectral method for non-periodic BVPs on [-1, 1]. Basis: Chebyshev polynomials T_k(x) = cos(k arccos x), k = 0, 1, .... Orthogonal w.r.t. weight 1/sqrt(1 - x^2): integral_{-1}^1 T_k(x) T_m(x)/sqrt(1-x^2) dx = (pi/2) delta_{km} (k, m >= 1); pi for k = m = 0. Approximate u(x) ≈ u_N(x) = sum_{k=0}^N a_k T_k(x). Collocation points: x_j = cos(j pi/N), j = 0, ..., N (Chebyshev-Gauss-Lobatto; cluster near endpoints). Derivative matrix D_{jm} = dT_k/dx(x_j) (compute from recurrence). Explicit: D^{(1)}_{jm} = ... has closed form (Trefethen). Higher derivatives: D^{(m)} = (D^{(1)})^m (matrix power). Solve BVP: discretize, apply BCs (rows for boundary points), solve linear system. Convergence: exponential for analytic u (||u - u_N|| <= C rho^{-N} ||u||, rho > 1 related to largest Bernstein ellipse where u analytic). Aliasing: Chebyshev grid aliasing (deal with 2/3 rule analog). BC: Dirichlet (set rows for boundary points to BC values); Neumann (use derivative matrix or tau method). Tau method: enforce BCs via projecting residual onto lower modes. Collocation: enforce BCs by setting u_N(x_0) = g_0, u_N(x_N) = g_N (replacing two equations). Chebyshev vs Legendre: both work; Chebyshev has FFT (fast), Legendre has simpler Gauss quadrature. Chebyshev-Gauss quadrature: integral_{-1}^1 f(x)/sqrt(1-x^2) dx ≈ (pi/N) sum_{j=1}^N f(x_j) (Chebyshev nodes of first kind x_j = cos((2j-1)pi/(2N))). Applications: boundary layers (high resolution near walls), eigenvalue problems (Orr-Sommerfeld for stability), optimal control, spectral element (tensor product on simple elements). Chebyshev on [a, b]: affine transform x -> (2x - a - b)/(b - a). Multi-dimensional: tensor product T_k(x) T_m(y) on rectangle; on triangle use Dubiner basis (collapsing coordinates). Preconditioned iterative solvers: finite-difference or finite-element preconditioner for spectral (Orszag). Time-stepping: explicit Delta t <= C/N^2 (CFL; spectral smallest grid spacing ~ 1/N^2 near endpoints). Implicit for stiff. ✓',
  'ch07p5_chebyshev_spectral',
  'formula_recall',
  ['Chebyshev spectral', 'non-periodic BVP', 'Chebyshev polynomials', 'collocation points', 'exponential convergence']
)

add(
  'What is the pseudospectral method and how do you handle nonlinear terms?',
  'Pseudospectral (collocation) method for nonlinear PDEs. Setup: PDE u_t = L u + N(u) where L linear, N nonlinear. Spectral representation u_N = sum hat u_k e^{ikx} (Fourier; or Chebyshev). Linear part: in spectral space, hat u_k\' = L_k hat u_k (diagonal; easy). Nonlinear part N(u): pseudospectral evaluation. (1) Compute u_N(x_j) at grid points (inverse FFT from hat u_k). (2) Compute N(u_N(x_j)) pointwise (in physical space; e.g., u^2 = u_N(x_j) * u_N(x_j)). (3) FFT N(u_N) back to spectral: hat N_k. (4) Update hat u_k\' = L_k hat u_k + hat N_k. Time step: explicit (RK4) for nonlinear, implicit for linear (IMEX): hat u_k^{n+1} = (hat u_k^n + Delta t hat N_k^n)/(1 - Delta t L_k) (linear implicit). Why pseudospectral (vs pure Galerkin)? Nonlinear products in spectral space are convolutions (O(N^2) per step); in physical space pointwise (O(N) + FFT O(N log N), much faster). Aliasing: nonlinear product creates modes beyond N (e.g., e^{ikx}·e^{imx} = e^{i(k+m)x}, but k+m may exceed N/2, aliasing back). Dealiasing: (a) 3/2 rule (zero-pad to 3N/2 modes before product, then truncate). (b) 2/3 rule (zero out modes |k| > N/3 after each step; removes aliased modes). (c) Phase shifting (less common). Without dealiasing: nonlinear instability may develop. Orszag two-thirds rule: keep modes |k| <= N/3, zero N/3 < |k| <= N/2; loses some resolution but stable. Applications: incompressible Navier-Stokes (pseudo-spectral with projection for incompressibility; vorticity-streamfunction or primitive variables + pressure projection), turbulence (DNS, 1024^3 modes), MHD, Boussinesq convection, nonlinear Schrodinger (split-step Fourier: linear part exactly in Fourier, nonlinear part in physical). Convergence: spectral (exponential) for smooth u. Cost: O(N log N) per step (FFT). Stability: explicit Delta t <= C/N (advection) or C/N^2 (diffusion); semi-implicit relaxes this. Resolution: N ~ 10^2-10^3 per dimension typical; petascale DNS N ~ 10^4. ✓',
  'ch07p5_pseudospectral_nonlinear',
  'problem_solving',
  ['pseudospectral', 'nonlinear', 'collocation', 'aliasing dealiasing', 'Orszag rule']
)

add(
  'What are spectral methods for the incompressible Navier-Stokes equations?',
  'Spectral methods for incompressible Navier-Stokes. Equations: u_t + (u · grad) u = -grad p + nu Delta u + f (momentum), div u = 0 (incompressibility), in periodic box [0, 2 pi]^3 (homogeneous turbulence) or with no-slip walls (channel flow). Projection method (Chorin 1968): (1) Intermediate velocity u* = u^n + Delta t [-((u·grad)u)^n + nu Delta u^n + f^n] (no pressure). (2) Projection: u^{n+1} = u* - Delta t grad p, with div u^{n+1} = 0. Take divergence: 0 = div u* - Delta t Delta p => Delta p = div u*/Delta t (Poisson for pressure; solve in Fourier: hat p_k = i k · hat u*_k/(Delta t |k|^2)). (3) u^{n+1} = u* - Delta t grad p (project onto divergence-free). In Fourier (periodic): each mode k != 0 has projection P_k = I - k k^T/|k|^2 (Leray projection). hat u_k = P_k hat u_k (removes compressible part). Nonlinear term: pseudospectral. (u·grad)u = div(u ⊗ u) (conservative form; better conservation). Compute u ⊗ u in physical, FFT, project. Convection form (u·grad)u: pseudospectral. Skew-symmetric form (combines both; less aliasing). Vorticity-streamfunction (2D): omega = curl u, psi streamfunction (u = curl psi). omega_t + (u·grad) omega = nu Delta omega. Poisson: Delta psi = -omega. Solve in Fourier: hat omega_k\' = -FFT[(u·grad)omega] - nu |k|^2 hat omega_k. psi from omega via hat psi_k = -hat omega_k/|k|^2. u = curl psi in Fourier: hat u_k = i k_perp hat psi_k (2D). Boundary: no-slip walls require Chebyshev in wall-normal direction, Fourier in streamwise/spanwise (Kim-Moin-Moser 1987 for channel). Time-stepping: Crank-Nicolson for viscous (implicit, stiff), Adams-Bashforth for convective (explicit). Dealiasing: 2/3 rule. Resolution: Re_tau = 180 channel needs 128^3; Re_tau = 1000 needs 1024^3; Re_tau = 5000 needs 8192^3 (petascale). Stability: CFL Delta t <= C min(h/|u|, h^2/nu) (viscous and convective). Pressure: exact projection or iterative (Uzawa, SIMPLE). ✓',
  'ch07p5_spectral_navier_stokes',
  'problem_solving',
  ['spectral Navier-Stokes', 'incompressible', 'projection method', 'Leray projection', 'vorticity streamfunction']
)

add(
  'How do you choose between finite difference, finite element, and spectral methods?',
  'Choosing between FD, FEM, spectral. Factors: (1) Geometry: simple (rectangular, periodic) -> FD or spectral (Fourier). Complex (curved, unstructured) -> FEM (handles arbitrary triangulations) or spectral element. (2) Smoothness: smooth/analytic solution -> spectral (exponential convergence). Rough/discontinuous (shocks, corners) -> low-order FEM/FD (spectral Gibbs oscillations near discontinuities). (3) Accuracy needed: low (1-5%) -> FD. Medium -> FEM. High (spectral accuracy for turbulence, quantum) -> spectral. (4) Cost: FD cheapest per DOF (sparse, local). FEM sparse but more setup (mesh, assembly). Spectral dense O(N^2)-O(N^3) but N small for given accuracy; FFT helps (O(N log N)). (5) Boundary conditions: complex BC, mixed, Robin -> FEM (natural handling via weak form). Simple -> FD. Spectral needs special treatment (tau, penalty). (6) Conservation: FEM good for conservation (Galerkin). DG excellent (local conservation). FD with finite-volume flux form. Spectral in Fourier: spectral conservation. (7) Adaptivity: hp-FEM best (combined h and p refinement). FD h-refinement with AMR (Berger-Oliger). Spectral: limited adaptivity (domain decomposition). (8) Stability: FD upwind/TVD for shocks. FEM stabilized (SUPG, GLS). DG upwind flux. Spectral: filters for Gibbs. (9) Implementation: FD simplest (few lines). FEM complex (mesh generators, assemblers; FEniCS, deal.II libraries). Spectral moderate (FFT-based). (10) Parallel: FEM and DG naturally parallel (element-local). FD structured grid (good for vector/SIMD). Spectral FFT parallel (slab/pencil decomposition). Recommendations: heat/wave eq on rectangle -> FD or FEM. Elliptic on complex geometry -> FEM. Hyperbolic conservation with shocks -> DG or FV (WENO). Incompressible turbulence -> pseudo-spectral (Fourier). Compressible flow -> DG or WENO-FD. Structural mechanics -> FEM. Quantum/chemistry -> spectral. Weather/climate -> spectral element. General-purpose PDE: FEM (most flexible); use FD for prototyping; spectral for smooth problems. ✓',
  'ch07p5_method_comparison',
  'formula_recall',
  ['FD vs FEM vs spectral', 'choosing method', 'geometry smoothness', 'accuracy cost', 'adaptivity']
)

// ============================================================
// SECTION 5 — MULTIGRID, ADI & BOUNDARY ELEMENT METHODS (5 items)
// ============================================================
add(
  'What is the multigrid method and why is it optimal for elliptic problems?',
  'Multigrid method. Idea: solve elliptic PDE (e.g., Poisson) on hierarchy of grids (fine -> coarse). Smooth error on fine grid (relaxation: Jacobi, Gauss-Seidel), then correct on coarse grid (where smooth error is well-resolved), recurse. Components: (1) Smoother: Jacobi, Gauss-Seidel, ILU. Reduces HIGH-frequency error (oscillatory) but not low-frequency (smooth). (2) Restriction: transfer residual from fine to coarse (full weighting, injection). (3) Prolongation: interpolate correction from coarse to fine (linear, bilinear). (4) Coarse-grid operator: discretize PDE on coarse grid (or Galerkin: A_coarse = R A_fine P). V-cycle: (1) Pre-smooth on fine (nu_1 iterations). (2) Compute residual r = b - A x. (3) Restrict r to coarse: r_c = R r. (4) Solve A_c e_c = r_c (recurse, or exact on coarsest). (5) Prolong e_c to fine: e = P e_c. (6) Correct x = x + e. (7) Post-smooth (nu_2 iterations). W-cycle: two coarse recursions per level (more expensive but more robust). Full Multigrid (FMG): start on coarsest, solve, prolong to finer, V-cycle; nest. Complexity: V-cycle O(N) work (one sweep). FMG O(N) total (optimal; converges in O(1) V-cycles to discretization accuracy). Compare: Jacobi O(N^2), SOR O(N^{1.5}), direct O(N^{1.5}-N^3). Convergence factor: rho < 0.1 typical per V-cycle (independent of N; "textbook multigrid"). Conditions: elliptic (smoother reduces high freq); regular grid/coarsening. For anisotropic problems (strong coefficient in one direction): semi-coarsening (coarsen only in strong direction) or alternating line smoothers. For complex geometry: algebraic multigrid (AMG): coarsen based on matrix entries, not geometry; works for unstructured. Geometric multigrid: uses mesh hierarchy. MG for nonlinear (FAS: Full Approximation Scheme): solve nonlinear on each level, no separate residual equation. MG for time-dependent: space-time MG, parabolic MG. MG as preconditioner: MGCG (CG accelerated by MG). Applications: Poisson (pressure Poisson in Navier-Stokes), linear elasticity, diffusion, Laplacian eigenvalue (Rayleigh quotient MG). Software: Hypre, ML (Trilinos), AMGCL, PyAMG. ✓',
  'ch07p5_multigrid',
  'formula_recall',
  ['multigrid', 'V-cycle W-cycle FMG', 'smoother restriction prolongation', 'O(N) optimal', 'AMG']
)

add(
  'What is the alternating direction implicit (ADI) method for parabolic PDEs?',
  'Alternating Direction Implicit (ADI) method. For 2D parabolic u_t = alpha (u_{xx} + u_{yy}). Direct implicit requires solving 2D system (large). ADI splits into two 1D implicit solves per step. Peaceman-Rachford (1955): U^* = U^n + (Delta t/2) alpha (delta_xx U^* + delta_yy U^n) (implicit in x, explicit in y). U^{n+1} = U^* + (Delta t/2) alpha (delta_xx U^* + delta_yy U^{n+1}) (implicit in y, explicit in x). Each sub-step is tridiagonal solve (fast). Second-order accurate O(Delta t^2 + Delta x^2 + Delta y^2). Unconditionally stable. Doublas-Rachford: variant for 3D (less accurate, O(Delta t)). Mitchell-Fairweather: higher-order. Fractional step (Yanenko): for general operator L = L_1 + L_2 + ..., split: (I - Delta t L_1) U^* = U^n; (I - Delta t L_2) U^{**} = U^*; ...; U^{n+1} = U^{(last)}. First-order accurate (unless corrections), unconditionally stable. Strang splitting (for time-dependent): symmetric splitting (half-step L_1, full L_2, half L_1) for second-order. ADI for 3D: u_t = alpha (u_{xx} + u_{yy} + u_{zz}). Three sub-steps, each tridiagonal in one direction. Cost: O(N) per step (vs O(N^{1.5}) for direct 3D implicit). Stability: unconditional. Accuracy: O(Delta t^2) for Peaceman-Rachford 2D; O(Delta t) for some 3D variants. Boundary conditions: intermediate values U^* need BC; use physical BC plus Delta t correction (Mitchell). Generalization: dimensional splitting for hyperbolic (dimensional ADI); LOD (locally one-dimensional). Applications: 2D/3D heat, diffusion, Black-Scholes multi-asset, reservoir simulation, groundwater. Software: standard in PDE libraries (FISHPACK, MUDPACK). Limitations: (1) Splits operator; may lose conservation. (2) BC handling subtle. (3) For systems, stability may degrade. (4) Coordinate-aligned (not for unstructured; use IMEX instead). IMEX (Implicit-Explicit): modern alternative; implicit for stiff (diffusion), explicit for non-stiff (advection); handles unstructured via FEM. ✓',
  'ch07p5_adi_method',
  'formula_recall',
  ['ADI', 'Peaceman-Rachford', 'alternating direction', 'tridiagonal solve', 'fractional step']
)

add(
  'What is the boundary element method (BEM) and how does it use Green\'s functions?',
  'Boundary Element Method (BEM). Idea: reformulate PDE as boundary integral equation (BIE) using Green\'s functions; discretize only the BOUNDARY (not the volume). Setup: Laplace or Poisson in domain D. Green\'s representation: u(x) = integral_{∂D} [G(x, y) partial u/partial n(y) - partial G/partial n(y) u(y)] dS_y (for x in D). Boundary limit (x -> ∂D): yields BIE relating u and partial u/partial n on ∂D. For Dirichlet (u given on ∂D): solve for partial u/partial n (hypersingular BIE). For Neumann: solve for u (Fredholm second-kind). Discretization: (1) Mesh ∂D into elements (panels). (2) Approximate u, partial u/partial n as piecewise polynomial on panels. (3) Collocate BIE at panel centers (or Galerkin). (4) Solve linear system. Matrix: dense (each panel interacts with all others via Green\'s function); N = number of boundary DOFs (smaller than FEM volume DOFs). Cost: O(N^3) direct solve, O(N^2) matrix-vector. Acceleration: fast multipole method (FMM) O(N log N) or O(N); panel clustering (Hackbusch); H-matrices. Advantages: (1) Dimensional reduction (3D -> 2D boundary; 2D -> 1D). (2) Infinite domain natural (no truncation; Green\'s function decays at infinity). (3) High accuracy for smooth boundaries (panel methods). (4) Stress concentration / gradients directly from boundary. Disadvantages: (1) Dense matrices (vs sparse FEM). (2) Needs fundamental solution (Laplace, Helmholtz, Stokes OK; variable coefficients hard). (3) Hypersingular integrals (need regularization). (4) Non-symmetric matrices (usually). Applications: external aerodynamics (panel methods, potential flow), acoustics (Helmholtz BEM), electromagnetics (MoM, EFIE/MFIE), fracture mechanics (crack tip), Stokes flow (boundary integral for suspensions), seismology. Variants: (a) Indirect BEM: use single/double layer potentials as ansatz. (b) Direct BEM: use Green\'s representation. (c) Dual reciprocity BEM (DRBEM): handle nonhomogeneous via particular solutions. Coupled FEM-BEM: BEM for exterior (infinite), FEM for interior (complex geometry). Nyström method: alternative discretization (quadrature on boundary). For Helmholtz (acoustics): avoid spurious resonances (Burton-Miller, combined field). ✓',
  'ch07p5_boundary_element',
  'formula_recall',
  ['BEM', 'boundary integral', 'Green\'s function', 'panel method', 'fast multipole']
)

add(
  'What is the fast multipole method (FMM) and how does it accelerate BEM?',
  'Fast Multipole Method (FMM), Greengard-Rokhlin 1987. Problem: N-body interactions (e.g., BEM matrix-vector product, particle simulations) cost O(N^2) naively. FMM reduces to O(N) (or O(N log N)). Idea: hierarchical grouping; far-field interactions computed via multipole expansions, near-field directly. Algorithm: (1) Build octree (3D) / quadtree (2D): recursively subdivide domain into boxes; each level has 8 (or 4) children. Stop when ~few points per leaf. (2) Multipole-to-local (M2L): for each box, the potential due to far-away sources is approximated by a multipole expansion (Legendre / spherical harmonic) centered at box center. Convert to local expansion around target box center. (3) Upward pass: compute multipole expansions at each level (leaf -> root), combining children expansions via translation (M2M). (4) Downward pass: compute local expansions at each level (root -> leaf), via L2L (local-to-local translation) and M2L. (5) Evaluate: at each target point, sum local expansion (far field) + direct interactions with neighbors (near field). Accuracy: controllable by expansion order p (number of multipoles); error ~ (a/d)^p where a = box size, d = distance; typical p = 10-20 for 1e-10 accuracy. Cost: O(N) for fixed p (each point interacts with O(1) boxes at each level; log N levels => O(N log N) or O(N) with proper FMM). Applications: BEM (matrix-vector product in iterative solver: GMRES + FMM), N-body simulations (stars, molecules), electrostatics (Poisson-Boltzmann), radar cross-section (MoM). Variants: (a) Black-box FMM (Martinsson): kernel-independent, uses Chebyshev interpolation. (b) Kernel-independent FMM (Ying-Biros-Zorin): uses equivalent source densities. (c) Periodic FMM (Ewald): for periodic BC (crystallography). (d) Adaptive FMM: variable tree depth (non-uniform distributions). (e) Directional FMM: for oscillatory kernels (Helmholtz high-frequency; Engquist-Ying). Modern: GPU FMM (fast), distributed FMM (petascale). Software: ExaFMM, ScalFMM, PVFMM. History: Greengard-Rokhlin 1987 (1e-6 speedup for 10^6 particles); now standard in computational physics. Without FMM: BEM limited to ~10^4 DOFs; with FMM: 10^7-10^8 DOFs. ✓',
  'ch07p5_fast_multipole',
  'formula_recall',
  ['FMM', 'fast multipole', 'Greengard-Rokhlin', 'multipole expansion', 'O(N) N-body']
)

add(
  'What are level set methods for interface tracking and free boundary problems?',
  'Level set method (Osher-Sethian 1988). Track moving interface Gamma(t) as zero level set of a higher-dimensional function phi(x, t): Gamma(t) = {x : phi(x, t) = 0}. phi > 0 one side, phi < 0 other side (signed distance function typically: phi = signed distance to Gamma). Motion: interface moves with velocity v(x, t) (normal component v_n). Level set equation: phi_t + v · grad phi = 0, or phi_t + v_n |grad phi| = 0 (v_n given; tangential doesn\'t affect interface). Solve as Hamilton-Jacobi PDE. Numerical: (1) High-order upwind (WENO, Godunov) for spatial discretization. (2) TVD-RK for time. (3) Reinitialization: |grad phi| = 1 (signed distance); solve d phi/d tau + sgn(phi_0)(|grad phi| - 1) = 0 (Sussman) to keep phi well-conditioned. (4) Extension of velocity: extend v_n off interface smoothly (PDE extension). Advantages: (1) Handles topology change (merging, splitting) automatically (no special logic). (2) Geometric quantities easy: normal n = grad phi/|grad phi|, curvature kappa = div(grad phi/|grad phi|). (3) 2D/3D unified. (4) High-order accurate. Disadvantages: (1) Higher-dim representation (2D interface -> 3D phi). (2) Mass loss (reinitialization can lose mass; fix: mass-conserving reinit). (3) Sharp interface smeared over few cells. Variants: (a) Fast marching method (FMM, Sethian): for stationary Eikonal |grad T| = 1/F (front propagation with speed F); O(N log N), one-shot (not time-evolving). (b) Narrow band level set: solve only near interface (O(N) per step). (c) Particle level set: combine with Lagrangian markers for sharpness. (d) Diffuse interface (phase field): alternative; Cahn-Hilliard for interface. Applications: (1) Two-phase flow (water-air, with surface tension). (2) Combustion (flame front). (3) Image processing (segmentation, Mumford-Shah). (4) Crystal growth, epitaxy. (5) Computer graphics (fluid animation, terrain). (6) Geometry (curve/surface evolution, mean curvature flow). (7) Optimization (shape optimization, level set method for topology). Coupled with Navier-Stokes: immersed interface, ghost fluid (Fedkiw) for sharp jump conditions. ✓',
  'ch07p5_level_set',
  'formula_recall',
  ['level set', 'Osher-Sethian', 'interface tracking', 'Hamilton-Jacobi', 'reinitialization']
)

// ============================================================
// SECTION 6 — WORKED PROBLEMS (7 items)
// ============================================================
add(
  'How do you solve u_t = u_{xx} on [0,1] with u(0,t)=u(1,t)=0 and u(x,0)=sin(pi x) using FTCS with Delta x=0.1, Delta t=0.001?',
  'FTCS scheme for u_t = u_{xx} (alpha = 1) on [0, 1], Dirichlet u = 0 at both ends, IC u(x, 0) = sin(pi x). Grid: Delta x = 0.1 (N = 10, so 9 interior points x_j = 0.1, 0.2, ..., 0.9), Delta t = 0.001. Courant number r = alpha Delta t/Delta x^2 = 1 · 0.001/0.01 = 0.1. Stability: r <= 0.5 ✓ (stable). FTCS: U_j^{n+1} = U_j^n + r (U_{j+1}^n - 2 U_j^n + U_{j-1}^n) = U_j^n + 0.1 (U_{j+1}^n - 2 U_j^n + U_{j-1}^n). Initial: U_j^0 = sin(pi x_j) = sin(0.1 pi j), j = 1, ..., 9. Values: sin(0.1 pi) ≈ 0.309, sin(0.2 pi) ≈ 0.588, sin(0.3 pi) ≈ 0.809, sin(0.4 pi) ≈ 0.951, sin(0.5 pi) = 1, sin(0.6 pi) ≈ 0.951, ... (symmetric). Step 1 (n = 0 -> 1): U_j^1 = U_j^0 + 0.1 (U_{j+1}^0 - 2 U_j^0 + U_{j-1}^0). For j = 5 (middle, x = 0.5, U_5^0 = 1, U_4^0 = U_6^0 ≈ 0.951): U_5^1 = 1 + 0.1 (0.951 - 2·1 + 0.951) = 1 + 0.1 (-0.098) = 1 - 0.0098 = 0.9902. For j = 1 (x = 0.1, U_1^0 = 0.309, U_0^0 = 0 (BC), U_2^0 = 0.588): U_1^1 = 0.309 + 0.1 (0.588 - 0.618 + 0) = 0.309 + 0.1 (-0.030) = 0.306. Exact solution: u(x, t) = sin(pi x) e^{-pi^2 t}. At t = 0.001: u(0.5, 0.001) = 1 · e^{-pi^2 · 0.001} ≈ 1 · e^{-0.00987} ≈ 1 - 0.00987 + ... ≈ 0.9902 ✓ (matches FTCS step 1). The first eigenmode sin(pi x) decays as e^{-pi^2 t}, rate pi^2 ≈ 9.87. FTCS captures this exactly at first step (because sin is an eigenfunction and FTCS amplification factor g = 1 - 4 r sin^2(k Delta x/2); for k = pi, Delta x = 0.1: sin^2(pi · 0.05) = sin^2(0.157) ≈ 0.0245; g = 1 - 4·0.1·0.0245 = 1 - 0.00980 ≈ 0.9902 ✓; matches e^{-pi^2 Delta t} ≈ 0.9902 to leading order). Long-time: U decays like (0.9902)^n. ✓',
  'ch07p5_worked_ftcs_heat',
  'problem_solving',
  ['worked FTCS', 'heat equation', 'sin(pi x)', 'Courant r=0.1', 'eigenmode decay']
)

add(
  'How do you analyze the stability of the FTCS scheme using von Neumann analysis?',
  'Von Neumann stability of FTCS for u_t = alpha u_{xx}. Scheme: (U_j^{n+1} - U_j^n)/Delta t = alpha (U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/Delta x^2. Let r = alpha Delta t/Delta x^2. U_j^{n+1} = U_j^n + r (U_{j+1}^n - 2 U_j^n + U_{j-1}^n). Ansatz: U_j^n = g^n e^{i k j Delta x} (Fourier mode, wavenumber k, amplification factor g per step). Substitute: g^{n+1} e^{i k j Delta x} = g^n e^{i k j Delta x} + r (g^n e^{i k (j+1) Delta x} - 2 g^n e^{i k j Delta x} + g^n e^{i k (j-1) Delta x}). Divide by g^n e^{i k j Delta x}: g = 1 + r (e^{i k Delta x} - 2 + e^{-i k Delta x}) = 1 + r (2 cos(k Delta x) - 2) = 1 - 2 r (1 - cos(k Delta x)) = 1 - 4 r sin^2(k Delta x/2). So amplification factor g(k) = 1 - 4 r sin^2(k Delta x/2). Stability (von Neumann): |g(k)| <= 1 for all k. Since sin^2 in [0, 1], g in [1 - 4r, 1]. Need: 1 - 4r >= -1 (lower bound) AND 1 <= 1 (upper bound, automatic). So 4r <= 2, r <= 1/2. Equivalently: alpha Delta t/Delta x^2 <= 1/2, i.e., Delta t <= Delta x^2/(2 alpha). Physical: time step must be small enough that diffusion across Delta x (time scale Delta x^2/alpha) is resolved (at least 2 steps per diffusion time). If r > 1/2: |g| > 1 for some k (high frequency), perturbation grows -> unstable (oscillations blow up). Practical: choose r = 1/4 or 1/6 (safety margin). For Delta x = 0.1, alpha = 1: Delta t <= 0.005; use Delta t = 0.001 (r = 0.1, safe) or Delta t = 0.005 (r = 0.5, marginal). If Delta x halved to 0.05: Delta t <= 0.00125 (quartered), so cost increases 8x (4x more grid points × 2x more time steps). Severe restriction -> use implicit (BTCS or Crank-Nicolson) for stiff diffusion. ✓',
  'ch07p5_worked_von_neumann_ftcs',
  'problem_solving',
  ['worked von Neumann', 'FTCS stability', 'amplification factor', 'r <= 1/2', 'Fourier mode']
)

add(
  'How do you solve u_{tt} = u_{xx} with u(0,t)=u(1,t)=0, u(x,0)=sin(pi x), u_t(x,0)=0 using FD with CFL rho=1?',
  'FD for 1D wave eq u_{tt} = u_{xx} (c = 1) on [0, 1], Dirichlet BC, IC u(x, 0) = sin(pi x), u_t(x, 0) = 0. Choose Delta x = 0.1 (N = 10, 9 interior), CFL rho = c Delta t/Delta x = 1 (so Delta t = Delta x = 0.1). Scheme (3-level central): U_j^{n+1} = 2 U_j^n - U_j^{n-1} + rho^2 (U_{j+1}^n - 2 U_j^n + U_{j-1}^n). With rho = 1: U_j^{n+1} = 2 U_j^n - U_j^{n-1} + (U_{j+1}^n - 2 U_j^n + U_{j-1}^n) = U_{j+1}^n + U_{j-1}^n - U_j^{n-1}. Initial: U_j^0 = sin(pi x_j) = sin(0.1 pi j). U_j^1: use Taylor + PDE: U_j^1 = U_j^0 + Delta t · u_t(x_j, 0) + (Delta t^2/2) u_{tt}(x_j, 0) + ... = sin(pi x_j) + 0 + (0.1^2/2) · sin\'\'(pi x_j)·pi^2... wait, u_{tt} = u_{xx} = -pi^2 sin(pi x). So U_j^1 = sin(pi x_j) + (Delta t^2/2)(-pi^2 sin(pi x_j)) = sin(pi x_j)(1 - pi^2 Delta t^2/2) = sin(pi x_j)(1 - pi^2 · 0.005) ≈ sin(pi x_j)(1 - 0.0493) ≈ 0.951 sin(pi x_j). Or use discretized: U_j^1 = U_j^0 + (rho^2/2)(U_{j+1}^0 - 2 U_j^0 + U_{j-1}^0) = sin(pi x_j) + 0.5 (sin(pi x_{j+1}) - 2 sin(pi x_j) + sin(pi x_{j-1})) = sin(pi x_j) + 0.5 sin(pi x_j) (2 cos(pi Delta x) - 2) = sin(pi x_j) (1 + cos(0.1 pi) - 1) = sin(pi x_j) cos(0.1 pi) ≈ sin(pi x_j) · 0.951 ✓ (matches). Step n=1 -> 2: U_j^2 = U_{j+1}^1 + U_{j-1}^1 - U_j^0. For j = 5 (middle): U_5^2 = U_6^1 + U_4^1 - U_5^0 = 0.951 sin(0.6 pi) + 0.951 sin(0.4 pi) - sin(0.5 pi) = 0.951 · 0.951 + 0.951 · 0.951 - 1 = 0.904 + 0.904 - 1 = 0.808. Exact: u(0.5, 0.2) = sin(0.5 pi) cos(pi · 0.2) = 1 · cos(0.2 pi) = cos(0.628) ≈ 0.809 ✓. CFL = 1 gives EXACT solution for single Fourier mode (since amplification g = 2 cos(k Delta t)·? ... for rho=1, scheme is exact for wave eq; captures F(x+t) + G(x-t) exactly at grid points). ✓',
  'ch07p5_worked_fd_wave_cfl1',
  'problem_solving',
  ['worked FD wave', 'CFL rho=1', 'exact for Fourier mode', 'three-level scheme', 'initial step Taylor']
)

add(
  'How do you solve Laplace equation on the unit square with u=0 on three sides and u=1 on top using 5-point stencil?',
  'Laplace Delta u = 0 on unit square [0,1]×[0,1], BC u(x, 0) = 0, u(0, y) = 0, u(1, y) = 0 (three sides grounded), u(x, 1) = 1 (top at potential 1). 5-point stencil with Delta x = Delta y = h = 0.25 (N = 4, 3×3 = 9 interior points). Stencil: (u_{i+1,j} + u_{i-1,j} + u_{i,j+1} + u_{i,j-1} - 4 u_{i,j})/h^2 = 0 => u_{i,j} = (1/4)(u_{i+1,j} + u_{i-1,j} + u_{i,j+1} + u_{i,j-1}). Label interior points (i, j), i, j = 1, 2, 3 (with i=0, j=0 boundary, i=4, j=4 boundary). BC: u_{0,j} = 0, u_{4,j} = 0, u_{i,0} = 0, u_{i,4} = 1 (top). Equations: u_{i,j} = (1/4)(neighbors) for i, j = 1, 2, 3. By symmetry (left-right), u_{1,j} = u_{3,j}. So unknowns: u_{1,1}, u_{1,2}, u_{1,3}, u_{2,1}, u_{2,2}, u_{2,3} (6 unknowns; using symmetry). Actually full 9 with symmetry reduction. Equations (Gauss-Seidel iteration): Start with u = 0 except top. Iterate. Solution (after convergence): by symmetry and the boundary, u is approximately: u_{2,3} (top middle, neighbors: u_{1,3}, u_{3,3}, u_{2,4}=1, u_{2,2}) = (1/4)(u_{1,3} + u_{1,3} + 1 + u_{2,2}) (using u_{3,3} = u_{1,3}). Solving all 9 (or 6) equations: final values approximately u_{1,1} ≈ 0.018, u_{2,1} ≈ 0.027, u_{1,2} ≈ 0.071, u_{2,2} ≈ 0.098, u_{1,3} ≈ 0.214, u_{2,3} ≈ 0.281 (approximate, from Jacobi iteration). Exact solution (separation of variables): u(x, y) = sum_{n odd} (4/(n pi sinh(n pi))) sin(n pi x) sinh(n pi y). At (0.5, 0.5): u = sum 4/(n pi sinh(n pi)) · sin(n pi/2) · sinh(n pi/2). Dominant n=1: 4/(pi sinh(pi)) · 1 · sinh(pi/2) = 4 sinh(pi/2)/(pi sinh(pi)) = 4/(pi · 2 cosh(pi/2)) (sinh(pi) = 2 sinh(pi/2) cosh(pi/2)) = 2/(pi cosh(pi/2)) ≈ 2/(pi · 2.509) ≈ 0.254. So u(0.5, 0.5) ≈ 0.254 (exact) vs FD ≈ 0.098 (h = 0.25 too coarse; need finer grid). With h = 0.1 (N = 10), FD ≈ 0.250 (close to exact). ✓',
  'ch07p5_worked_laplace_square',
  'problem_solving',
  ['worked Laplace', '5-point stencil', 'unit square', 'Jacobi iteration', 'separation exact']
)

add(
  'How do you solve -u\'\' = x on [0,1] with u(0)=u(1)=0 using linear FEM with h=0.25?',
  'Linear FEM for -u\'\' = x on [0, 1], u(0) = u(1) = 0. Weak form: integral u\' v\' dx = integral x v dx for all v in H^1_0. Mesh: h = 0.25, nodes x_0 = 0, x_1 = 0.25, x_2 = 0.5, x_3 = 0.75, x_4 = 1. Interior unknowns U_1, U_2, U_3 (U_0 = U_4 = 0). Hat functions phi_i, i = 1, 2, 3. Stiffness matrix K_{ij} = integral phi_i\' phi_j\' dx. Element stiffness (length h): K^{elem} = (1/h) [[1, -1], [-1, 1]]. Assemble (1D): K = (1/h) tridiagonal[-1, 2, -1] for interior. h = 0.25, 1/h = 4. K = 4 · [[2, -1, 0], [-1, 2, -1], [0, -1, 2]] = [[8, -4, 0], [-4, 8, -4], [0, -4, 8]]. Load vector F_i = integral x phi_i dx. Element load: integral_{x_{i-1}}^{x_{i+1}} x phi_i(x) dx = x_i · h (centroid value times h, for linear hat). F_1 = 0.25 · 0.25 = 0.0625. F_2 = 0.5 · 0.25 = 0.125. F_3 = 0.75 · 0.25 = 0.1875. (Actually integral x phi_i over support [x_{i-1}, x_{i+1}]: phi_i = (x - x_{i-1})/h on [x_{i-1}, x_i], (x_{i+1} - x)/h on [x_i, x_{i+1}]. integral x phi_i = (1/h)[integral_{x_{i-1}}^{x_i} x(x - x_{i-1}) dx + integral_{x_i}^{x_{i+1}} x(x_{i+1} - x) dx] = (1/h)[x_i^2 h/2 - x_{i-1} x_i h + x_{i-1}^2 h/2 + x_{i+1}^2 h/2 - x_i^2 h/2 ... let me just use midpoint rule: ≈ x_i · area = x_i · h for each half-element, total 2 · x_i · h/2 = x_i h). So F_i = x_i h. F_1 = 0.25·0.25 = 0.0625 ✓, F_2 = 0.5·0.25 = 0.125 ✓, F_3 = 0.75·0.25 = 0.1875 ✓. Solve K U = F: [[8,-4,0],[-4,8,-4],[0,-4,8]] [U_1,U_2,U_3]^T = [0.0625, 0.125, 0.1875]^T. By symmetry (x -> 1-x, RHS x -> 1-x, solution u(x) -> u(1-x) implies u(0.25) = u(0.75)? No: -u\'\' = x is not symmetric; solution u(x) = x(1 - x^2)/6 = (x - x^3)/6; u(0.25) = (0.25 - 0.0156)/6 ≈ 0.0391; u(0.5) = (0.5 - 0.125)/6 = 0.0625; u(0.75) = (0.75 - 0.422)/6 ≈ 0.0547). Solve: row 1: 8 U_1 - 4 U_2 = 0.0625. Row 2: -4 U_1 + 8 U_2 - 4 U_3 = 0.125. Row 3: -4 U_2 + 8 U_3 = 0.1875. Solve: U_1 ≈ 0.0391, U_2 ≈ 0.0625, U_3 ≈ 0.0547 ✓ (matches exact u at nodes; FEM with linear elements is exact at nodes for this smooth problem — "superconvergence" / nodal exactness for 1D -u\'\' = f with f linear). ✓',
  'ch07p5_worked_fem_1d_poisson',
  'problem_solving',
  ['worked FEM 1D', 'Poisson', 'linear elements', 'stiffness matrix', 'nodal exactness']
)

add(
  'How do you analyze the Crank-Nicolson scheme for the heat equation?',
  'Crank-Nicolson (CN) for u_t = alpha u_{xx}. Scheme: (U_j^{n+1} - U_j^n)/Delta t = (alpha/2) [(U_{j+1}^n - 2 U_j^n + U_{j-1}^n)/Delta x^2 + (U_{j+1}^{n+1} - 2 U_j^{n+1} + U_{j-1}^{n+1})/Delta x^2]. Average of FTCS (explicit, evaluated at n) and BTCS (implicit, at n+1). Let r = alpha Delta t/Delta x^2. Rearrange: -r/2 U_{j-1}^{n+1} + (1 + r) U_j^{n+1} - r/2 U_{j+1}^{n+1} = r/2 U_{j-1}^n + (1 - r) U_j^n + r/2 U_{j+1}^n. Matrix: (I + r/2 T) U^{n+1} = (I - r/2 T) U^n where T = tridiagonal[-1, 2, -1]. Solve tridiagonal system each step (O(N) work). Truncation: O(Delta t^2 + Delta x^2) (second-order in time and space; better than FTCS/BTCS which are first-order in time). Derivation: Taylor expand, central difference in time (n + 1/2). Stability (von Neumann): g = (1 - 2 r sin^2(k Delta x/2))/(1 + 2 r sin^2(k Delta x/2)). |g|^2 = (1 - 2 r s)^2/(1 + 2 r s)^2 where s = sin^2 in [0, 1]. |g| <= 1 iff |1 - 2rs| <= |1 + 2rs| = 1 + 2rs (since 1 + 2rs > 0). |1 - 2rs| <= 1 + 2rs iff 1 - 2rs <= 1 + 2rs (i.e., rs >= 0 ✓) AND -(1 - 2rs) <= 1 + 2rs (i.e., 2rs - 1 <= 1 + 2rs, i.e., -1 <= 1 ✓). So |g| <= 1 always (for r > 0). Unconditionally stable (any Delta t). Accuracy: O(Delta t^2) means can use larger Delta t than FTCS (which needs Delta t <= Delta x^2/(2alpha)); CN can use Delta t ~ Delta x (10-100x larger). Cost per step: tridiagonal solve O(N) (same as FTCS per step, but FTCS needs many more steps). Total cost: CN much cheaper for given accuracy. Comparison: FTCS: O(Delta t + Delta x^2), conditionally stable (r <= 1/2). BTCS: O(Delta t + Delta x^2), unconditionally stable. CN: O(Delta t^2 + Delta x^2), unconditionally stable (BEST). Oscillations: for very stiff problems (large r), CN may show oscillations (not |g| < 1 strictly; |g| -> 1 from below, but sign flips for high freq if r > 1, causing spurious oscillations). Fix: theta-method with theta > 1/2 (e.g., theta = 0.55); or Rannacher smoothing (half BTCS steps first). ✓',
  'ch07p5_worked_crank_nicolson',
  'problem_solving',
  ['worked Crank-Nicolson', 'heat eq', 'unconditionally stable', 'second-order', 'von Neumann']
)

add(
  'How do you solve the advection equation u_t + 2 u_x = 0 using upwind with Delta x = 0.1, Delta t = 0.04 and IC u(x,0) = sin(x)?',
  'Upwind scheme for u_t + 2 u_x = 0 (a = 2 > 0, so upwind = backward difference in x). Delta x = 0.1, Delta t = 0.04. CFL mu = a Delta t/Delta x = 2 · 0.04/0.1 = 0.8. Stability: 0 <= mu <= 1 ✓ (stable). Scheme: U_j^{n+1} = U_j^n - mu (U_j^n - U_{j-1}^n) = U_j^n - 0.8 (U_j^n - U_{j-1}^n) = 0.2 U_j^n + 0.8 U_{j-1}^n. Initial: U_j^0 = sin(x_j) = sin(0.1 j) (on periodic domain or infinite; let\'s use periodic [0, 2 pi] with 63 points, j = 0, ..., 62, x_j = 0.1 j). Step 1 (n=0 -> 1): U_j^1 = 0.2 U_j^0 + 0.8 U_{j-1}^0 = 0.2 sin(0.1 j) + 0.8 sin(0.1 (j-1)) = 0.2 sin(0.1 j) + 0.8 sin(0.1 j - 0.1). Expand: sin(0.1 j - 0.1) = sin(0.1 j) cos(0.1) - cos(0.1 j) sin(0.1). So U_j^1 = 0.2 sin(0.1 j) + 0.8 [sin(0.1 j) cos(0.1) - cos(0.1 j) sin(0.1)] = sin(0.1 j) [0.2 + 0.8 cos(0.1)] - 0.8 sin(0.1) cos(0.1 j) = sin(0.1 j) · [0.2 + 0.8 · 0.995] - 0.8 · 0.0998 · cos(0.1 j) = sin(0.1 j) · 0.996 - 0.0799 cos(0.1 j). Rewrite as R sin(0.1 j - phi): R = sqrt(0.996^2 + 0.0799^2) ≈ sqrt(0.992 + 0.00638) ≈ sqrt(0.998) ≈ 0.999. tan phi = 0.0799/0.996 ≈ 0.0802, phi ≈ 0.0800. So U_j^1 ≈ 0.999 sin(0.1 j - 0.0800) = 0.999 sin(x_j - 0.0800). Exact: u(x, t) = sin(x - 2 t) = sin(x - 0.08) at t = 0.04 ✓ (matches: amplitude 0.999 ≈ 1, phase 0.0800 ≈ 0.08). Slight amplitude damping (0.999 vs 1) due to numerical diffusion (artificial viscosity nu = (a Delta x/2)(1 - mu) = (2 · 0.1/2)(1 - 0.8) = 0.1 · 0.2 = 0.02; over Delta t = 0.04, damping factor e^{-nu k^2 Delta t} = e^{-0.02 · 1 · 0.04} = e^{-0.0008} ≈ 0.9992 ✓). Long-time: amplitude decays as (0.999)^n per step; after 100 steps (t = 4), amplitude ≈ 0.999^100 ≈ 0.905 (10% loss); after 1000 steps (t = 40), ≈ 0.37 (63% loss). Phase: phi per step = 0.0800, so after n steps, total phase = 0.0800 n. Exact phase should be 2 Delta t n = 0.08 n. Match ✓ (phase accurate to 4 digits). Conclusion: upwind captures advection accurately but with amplitude damping (numerical diffusion). For sharper profiles, use higher-order (Lax-Wendroff, WENO). ✓',
  'ch07p5_worked_upwind_advection',
  'problem_solving',
  ['worked upwind', 'advection', 'CFL mu=0.8', 'numerical diffusion', 'amplitude damping']
)

// ============================================================
// WRITE OUTPUT
// ============================================================
const output = {
  generatedAt: new Date().toISOString(),
  totalItems: items.length,
  subject: 'mathematics_formulas_volume_9_chapter_07_part_05',
  volume:
    'Volume 9 — Comprehensive Formula Encyclopedia, Chapter 7 Part 5 (Numerical Methods for PDEs — Finite Difference Methods, Stability Consistency Convergence and Lax-Richtmyer, CFL Condition and Von Neumann Analysis, Finite Element Method, Spectral and Pseudospectral Methods, Multigrid ADI and Boundary Element Methods, Worked Problems)',
  source: 'TRIZA Generated Formula Dataset',
  language: 'en',
  religionNeutral: true,
  items,
}

mkdirSync('data', { recursive: true })
writeFileSync('data/math-formulas-vol9-ch07p5.json', JSON.stringify(output, null, 2))
console.log(`Wrote ${items.length} items to data/math-formulas-vol9-ch07p5.json`)
